<?php
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx FAQ
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'Modzzz FAQ';

$aLangContent = array(

    '_sbs_txt_title_modzzz_faq' => 'FAQ',
    '_modzzz_faq' => 'FAQ',
    '_modzzz_faq_fans' => 'fans',
    '_modzzz_faq_add' => 'add',
    '_modzzz_faq_wall_added_new' => 'added new',
    '_modzzz_faq_wall_object' => 'faq',
    '_modzzz_faq_for_faq' => 'for %s',
    '_modzzz_faq_faq_single' => 'faq',
    '_modzzz_faq_faq_plural' => 'faq',
    '_modzzz_faq_user_unknown' => 'Unknown',
    '_modzzz_faq_disabled' => 'disabled',
    '_modzzz_faq_enabled' => 'enabled',
    '_modzzz_faq_block_help' => 'Did this Help You?',
    '_modzzz_faq_helpful_results' => '%d agreed',
    '_modzzz_faq_unhelpful_results' => '%d disagreed', 
    '_modzzz_faq_msg_rate_up' => 'FAQ Marked as Helpful',
    '_modzzz_faq_msg_rate_down' => 'FAQ Marked as Un-Helpful',
    '_modzzz_mark_help_already' => 'You have marked this FAQ already',
    '_modzzz_faq_found this helpful' => '%d member(s) found this helpful', 

    '_modzzz_faq_form_caption_snippet' => 'Snippet',
    '_modzzz_faq_form_info_snippet' => 'Snippet length cannot be greater than {0}',
    '_modzzz_faq_continue' => 'Continue',
 
    '_modzzz_faq_spy_post' => '<a href="{profile_link}">{profile_nick}</a> added new faq <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_faq_spy_post_change' => '<a href="{profile_link}">{profile_nick}</a> changed faq <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_faq_spy_rate' => '<a href="{profile_link}">{profile_nick}</a> rated faq <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_faq_spy_comment' => '<a href="{profile_link}">{profile_nick}</a> commented faq <a href="{entry_url}">{entry_title}</a>',

    '_modzzz_faq_sbs_change' => 'information was updated',
    '_modzzz_faq_sbs_comment' => 'new comment arrived',
    '_modzzz_faq_sbs_rate' => 'rating was updated',
 
    '_modzzz_faq_tab_featured' => 'Featured',
    '_modzzz_faq_tab_recent' => 'Recent',
    '_modzzz_faq_tab_top' => 'Top',
    '_modzzz_faq_tab_popular' => 'Popular',
    
	'_modzzz_faq_view_all' => 'View All', 
    '_modzzz_faq_daily_tips' => 'Daily Tips',

    '_modzzz_faq_block_submenu_main' => 'Main',
    '_modzzz_faq_block_submenu_add_faq' => 'Add',
    '_modzzz_faq_block_submenu_manage_faq' => 'Manage',
    '_modzzz_faq_block_submenu_pending_faq' => 'Non Active',

    '_modzzz_faq_block_actions' => 'Actions',
    '_modzzz_faq_block_rate' => 'Rate',    
    '_modzzz_faq_block_info' => 'Info',
    '_modzzz_faq_block_desc' => 'Description',
    '_modzzz_faq_block_photo' => 'Photos',
    '_modzzz_faq_block_video' => 'Videos',
    '_modzzz_faq_block_sound' => 'Sounds',
    '_modzzz_faq_block_files' => 'Files',
    '_modzzz_faq_block_file' => 'Files',
    '_modzzz_faq_block_comments' => 'Comments',
    '_modzzz_faq_block_latest_featured_faq' => 'Latest Featured FAQ',
    '_modzzz_faq_block_recent' => 'Recent FAQ',
    '_modzzz_faq_block_popular' => 'Popular FAQ',
    '_modzzz_faq_block_top' => 'Top Rated FAQ',
    '_modzzz_faq_block_search' => 'Search FAQ',
    '_modzzz_faq_block_faq_categories' => 'FAQ Categories',

    '_modzzz_faq_block_administration_owner' => 'Administration',
    '_modzzz_faq_block_users_faq' => 'User\'s FAQ',
    '_modzzz_faq_block_my_faq' => 'My FAQ',
    '_modzzz_faq_block_homepage' => 'Site FAQ',

    '_modzzz_faq_caption_add' => 'Add FAQ',
    '_modzzz_faq_caption_share_faq' => 'Share FAQ',
    '_modzzz_faq_caption_admin_actions' => 'Links',
    '_modzzz_faq_caption_pending_approval' => 'Not Active FAQ', 

    '_modzzz_faq_menu_root' => 'FAQ',
    '_modzzz_faq_menu_main' => 'FAQ Home',
    '_modzzz_faq_menu_recent' => 'Recent',
    '_modzzz_faq_menu_top_rated' => 'Top Rated',
    '_modzzz_faq_menu_popular' => 'Popular',
    '_modzzz_faq_menu_featured' => 'Featured',
    '_modzzz_faq_menu_tags' => 'Tags',
    '_modzzz_faq_menu_categories' => 'Categories',
    '_modzzz_faq_menu_calendar' => 'Calendar',
    '_modzzz_faq_menu_search' => 'Search',
    '_modzzz_faq_menu_view_faq' => 'Main',
    '_modzzz_faq_menu_view_comments' => 'Comments',
    '_modzzz_faq_menu_view_photos' => 'Photos',
    '_modzzz_faq_menu_view_videos' => 'Videos',
    '_modzzz_faq_menu_view_sounds' => 'Sounds',
    '_modzzz_faq_menu_view_files' => 'Files',
    '_modzzz_faq_menu_my_faq_profile' => 'FAQ',

    '_modzzz_faq_menu_admin_pending_approval' => 'Not Active',
    '_modzzz_faq_menu_admin_entries' => 'Admin FAQ',
    '_modzzz_faq_menu_admin_add_entry' => 'Add FAQ',
    '_modzzz_faq_menu_admin_settings' => 'Settings',
    
    '_modzzz_faq_page_title_home' => 'FAQ Home',
    '_modzzz_faq_page_title_calendar' => 'FAQ Calendar ',
    '_modzzz_faq_page_title_comments' => 'Comments',
    '_modzzz_faq_page_title_photos' => 'Photos',
    '_modzzz_faq_page_title_videos' => 'Videos',
    '_modzzz_faq_page_title_sounds' => 'Sounds',
    '_modzzz_faq_page_title_files' => 'Files',
    '_modzzz_faq_page_title_my_faq' => 'My FAQ',
    '_modzzz_faq_page_title_search' => 'FAQ Search',
    '_modzzz_faq_page_title_add' => 'Add FAQ', 
    '_modzzz_faq_page_title_edit' => 'Edit FAQ',
    '_modzzz_faq_page_title_administration' => 'FAQ Administration',
    '_modzzz_faq_page_title_browse' => 'Browse FAQ',
    '_modzzz_faq_page_title_pending_approval' => 'Not Active FAQ',
    '_modzzz_faq_page_title_search_results' => 'FAQ Search Results',
    '_modzzz_faq_page_title_browse_by_author' => '\'s faq',
    '_modzzz_faq_page_title_admin_faq' => 'Admin FAQ',
    '_modzzz_faq_page_title_browse_by_category' => 'Browse FAQ By Category: ',
    '_modzzz_faq_page_title_browse_by_tag' => 'Browse FAQ By Tag: ',
    '_modzzz_faq_page_title_browse_recent' => 'Recent FAQ',
    '_modzzz_faq_page_title_browse_random' => 'Daily FAQ', 
    '_modzzz_faq_page_title_browse_top_rated' => 'Top Rated FAQ',
    '_modzzz_faq_page_title_browse_popular' => 'Popular FAQ',
    '_modzzz_faq_page_title_browse_featured' => 'Featured FAQ',
    '_modzzz_faq_page_title_browse_by_day' => 'Browse FAQ By Day: ',
    '_modzzz_faq_page_title_tags' => 'FAQ Tags',
    '_modzzz_faq_page_title_categories' => 'FAQ Categories',
    '_modzzz_faq_page_title_upload_photos' => 'Add Photos',
    '_modzzz_faq_page_title_upload_videos' => 'Add Videos',
    '_modzzz_faq_page_title_upload_sounds' => 'Add Sounds',
    '_modzzz_faq_page_title_upload_files' => 'Add Files',

    '_modzzz_faq_msg_pending_approval' => 'this faq is not active, please wait until it will be activated',
    '_modzzz_faq_msg_faq_was_deleted' => 'FAQ was deleted',
    '_modzzz_faq_msg_removed_from_featured' => 'FAQ was removed from featured',
    '_modzzz_faq_msg_added_to_featured' => 'FAQ was added to featured',
    '_modzzz_faq_msg_photo_is_pending_approval' => 'Photo is not active',
    '_modzzz_faq_msg_you_have_pending_approval_faq' => 'You have <a href="%s">%d not active faq</a>',
    '_modzzz_faq_msg_you_have_no_faq' => 'You don\'t have any faq. <a href="%s">Click here</a> to add one.',
    '_modzzz_faq_msg_you_have_some_faq' => 'You have <a href="%s">%d faq(s)</a>. <a href="%s">Click here</a> to add more.',

    '_modzzz_faq_admin_delete' => 'Delete',
    '_modzzz_faq_admin_activate' => 'Activate',
    '_modzzz_faq_admin_add_new_faq' => 'Add New FAQ',
    '_modzzz_faq_admin_faq' => 'Admin FAQ',
    '_modzzz_faq_admin_settings' => 'Admin Settings',

    '_modzzz_faq_form_header_info' => 'FAQ\'s Info',
    '_modzzz_faq_form_header_images' => 'FAQ\'s Photos',
    '_modzzz_faq_form_header_videos' => 'FAQ\'s Videos',
    '_modzzz_faq_form_header_sounds' => 'FAQ\'s Sounds',
    '_modzzz_faq_form_header_files' => 'FAQ\'s Files',
    '_modzzz_faq_form_header_privacy' => 'Privacy Settings',
    '_modzzz_faq_form_caption_title' => 'Title',
    '_modzzz_faq_form_err_title' => 'Please enter from 3 to 100 characters',
    '_modzzz_faq_form_caption_desc' => 'Description',
    '_modzzz_faq_form_err_desc' => 'Please enter at least 20 characters',
    '_modzzz_faq_form_err_tags' => 'Please enter tags',
    '_modzzz_faq_form_caption_author_id' => 'Author',
    '_modzzz_faq_form_info_author' => 'Author profile ID number',
    '_modzzz_faq_form_caption_keyword' => 'Keyword',
    '_modzzz_faq_form_err_keyword' => 'Please enter from 3 to 100 characters',
    '_modzzz_faq_form_caption_category' => 'Category',
    '_modzzz_faq_form_err_category' => 'Category is invalid',    
    '_modzzz_faq_form_caption_images_choice' => 'Choose',
    '_modzzz_faq_form_info_images_choice' => 'You can choose several images from your "FAQ" category',
    '_modzzz_faq_form_caption_images_upload' => 'Upload',    
    '_modzzz_faq_form_info_images_upload' => 'Image will be placed in the "FAQ" category automatically',
    '_modzzz_faq_form_caption_videos_choice' => 'Choose',
    '_modzzz_faq_form_info_videos_choice' => 'You can choose several videos from your "FAQ" category',
    '_modzzz_faq_form_caption_videos_upload' => 'Upload',
    '_modzzz_faq_form_info_videos_upload' => 'Video will be placed in the "FAQ" category automatically',
    '_modzzz_faq_form_caption_sounds_choice' => 'Choose',
    '_modzzz_faq_form_info_sounds_choice' => 'You can choose several sounds from your "FAQ" category',
    '_modzzz_faq_form_caption_sounds_upload' => 'Upload',
    '_modzzz_faq_form_info_sounds_upload' => 'Sound will be placed in the "FAQ" category automatically',
    '_modzzz_faq_form_caption_files_choice' => 'Choose',
    '_modzzz_faq_form_info_files_choice' => 'Unclick checkbox to remove file from this faq',
    '_modzzz_faq_form_caption_files_upload' => 'Upload',
    '_modzzz_faq_form_info_files_upload' => 'File will be placed in the "FAQ" category and set as private automatically',
    '_modzzz_faq_form_caption_file_title' => 'Title:',
    '_modzzz_faq_form_caption_file_price' => 'Price:',
    '_modzzz_faq_form_caption_file_allow_purcase_to' => 'Allow purchase to:',
    '_modzzz_faq_form_caption_thumb_choice' => 'Choose thumbnail',
    '_modzzz_faq_form_info_thumb_choice' => 'You can choose any image from your "FAQ" category as faq thumbnail',
 

    '_modzzz_faq_action_title_edit' => 'Edit',
    '_modzzz_faq_action_title_delete' => 'Delete',
    '_modzzz_faq_action_title_share' => 'Share',
    '_modzzz_faq_action_add_to_featured' => 'Make Featured',    
    '_modzzz_faq_action_remove_from_featured' => 'Unfeature',
    '_modzzz_faq_action_add_faq' => 'Add FAQ',
    '_modzzz_faq_action_my_faq' => 'My FAQ',
    '_modzzz_faq_action_upload_photos' => 'Add Photos',
    '_modzzz_faq_action_upload_videos' => 'Add Videos',
    '_modzzz_faq_action_upload_sounds' => 'Add Sounds',
    '_modzzz_faq_action_upload_files' => 'Add Files',
    '_modzzz_faq_action_faq_home' => 'Home',

    '_modzzz_faq_privacy_view_faq' => 'View FAQ',
    '_modzzz_faq_privacy_comment' => 'Comment',
    '_modzzz_faq_privacy_rate' => 'Rate',
    '_modzzz_faq_privacy_upload_photos' => 'Upload Photos',
    '_modzzz_faq_privacy_upload_videos' => 'Upload Videos',
    '_modzzz_faq_privacy_upload_sounds' => 'Upload Sounds',
    '_modzzz_faq_privacy_upload_files' => 'Upload Files',
    '_modzzz_faq_privacy_edit_faq' => 'Edit FAQ',
    '_modzzz_faq_privacy_admins_only' => 'Admins Only',
    '_modzzz_faq_anonymous_note' => 'your name will not appear as the poster', 
    '_mma_faq_view_faq' => 'faq view faq', 
    '_mma_faq_browse' => 'faq browse', 
    '_mma_faq_search' => 'faq search', 
    '_mma_faq_add_faq' => 'faq add faq', 
    '_mma_faq_comments_delete_and_edit' => 'faq comments delete and edit', 
    '_mma_faq_edit_any_faq' => 'faq edit any faq', 
    '_mma_faq_delete_any_faq' => 'faq delete any faq', 
    '_mma_faq_mark_as_featured' => 'faq mark as featured', 
    '_mma_faq_approve_faq' => 'faq approve faq', 
    '_mma_faq_rate_help' => 'faq rate help', 

   	'_modzzz_faq_form_header_video_embed' => 'Video Embed',
   	'_modzzz_faq_form_caption_video_embed_code' => 'Embed Code',
   	'_modzzz_faq_block_video_embed' => 'External Video',
 	'_modzzz_faq_form_info_video_embed_code' => 'Enter either the URL or Embed Code for Youtube Video. Enter the Embed Code for other video sharing site (eg &lt;embed&gt;....&lt;/embed&gt;)',

    '_modzzz_faq_adm_stats' => 'Pending FAQ', 
	'_sys_module_faq' => 'FAQ', 
    '_modzzz_faq_block_calendar' => 'Calendar',  
    '_modzzz_faq_go' => 'Go',  
);