<?
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Listing
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'Modzzz Business Directory';

$aLangContent = array(

    '_modzzz_listing_fans' => 'fans',
    '_modzzz_listing_sbs_join' => 'new fan',
    '_modzzz_listing_block_fans' => 'Fans',
    '_modzzz_listing_block_fans_unconfirmed' => 'Unconfirmed Fans',
	'_modzzz_listing_block_my_listings_joined' => 'Joined Listings',
    '_modzzz_listing_caption_manage_fans' => 'Manage Fans',
    '_modzzz_listing_menu_view_fans' => 'Fans',
    '_modzzz_listing_page_title_fans' => 'Listing\'s Fans',
    '_modzzz_listing_action_manage_fans' => 'Manage Fans',
    '_modzzz_listing_privacy_view_fans' => 'View Fans',
    '_modzzz_listing_privacy_fans_only' => 'Fans Only',
    '_modzzz_listing_privacy_fans' => 'Fans',

    '_modzzz_listing_spy_join' => '<a href="{profile_link}">{profile_nick}</a> joined listing <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_listing_sbs_join' => 'new fan',
    '_modzzz_listing_page_title_browse_by_author_joined_listings' => '\'s joined listings',
    '_modzzz_listing_msg_joined_already' => 'You have already joined this listing',
    '_modzzz_listing_msg_joined_request_pending' => 'You have already joined this listing. Please wait while your request is processed by listing admin(s).',
    '_modzzz_listing_msg_join_success' => 'You have successfully joined this listing',
    '_modzzz_listing_msg_join_success_pending' => 'You have successfully joined this listing. Please wait while your request is processed by listing admin(s).',
	'_modzzz_listing_msg_leave_success' => 'You have successfully left this listing',
    '_modzzz_listing_form_caption_join_confirmation' => 'Join Confirmation',
    '_modzzz_listing_form_info_join_confirmation' => 'If enabled, listing admin(s) will have to confirm each user before he/she becomes a fan.',
    '_modzzz_listing_form_join_confirmation_disabled' => 'Disabled',
    '_modzzz_listing_form_join_confirmation_enabled' => 'Enabled',
    '_modzzz_listing_form_err_join_confirmation' => 'Join confirmation field must be 0 or 1',
    '_modzzz_listing_action_title_join' => 'Become Fan',
    '_modzzz_listing_action_title_leave' => 'Remove Fan',
    '_modzzz_listing_privacy_join' => 'Join',
 
    '_modzzz_listing_packages_empty' => 'There are no Business Packages', 
    '_modzzz_listing_package_description' => 'Description', 
    '_modzzz_listing_package_featured' => 'Featured', 

    '_modzzz_listing_featured_status' => 'Featured Status', 
    '_modzzz_listing_featured_until' => 'Featured until', 
    '_modzzz_listing_not_featured' => 'Not Featured', 
 	'_modzzz_listing_extend_featured' => 'Extend Featured Status',  
	'_modzzz_listing_purchase_featured' => 'Purchase Featured Status', 
	'_modzzz_listing_form_caption_currency' => 'Currency',  

    '_modzzz_listing_menu_packages' => 'Packages', 
    '_modzzz_listing_page_title_packages' => 'Business Packages', 
    '_modzzz_listing_block_packages' => 'Business Packages', 

    '_modzzz_listing_menu_view_forum' => 'Forum', 
    '_modzzz_listing_privacy_post_in_forum' => 'Post In Forum',
 
   	'_modzzz_listing_form_header_video_embed' => 'Video Embed',
   	'_modzzz_listing_caption_video_embed_code' => 'Embed Code',
   	'_modzzz_listing_block_video_embed' => 'External Video',
 
	'_modzzz_listing_caption_membership_view_filter' => 'Allow viewing by membership',
	'_modzzz_listing_err_membership_view_filter' => 'incorrect value', 
    '_modzzz_listing_info_membership_view_filter' => 'only these members will be able to view this business listing',
    '_modzzz_listing_membership_filter_none' => 'Allow All',	

    '_mma_listing_files_add' => 'listing files add',  
    '_mma_listing_photos_add' => 'listing photos add',  
    '_mma_listing_videos_add' => 'listing videos add',  
    '_mma_listing_sounds_add' => 'listing sounds add',  
	
    '_modzzz_listing_continue' => 'Continue',  
    '_modzzz_listing_admin_assign' => 'Assign to Claimant',  
    '_modzzz_listing_menu_manage_claims' => 'Claims',  
    '_modzzz_listing_claimed_by' => 'Claimed by',  
    '_modzzz_listing_on' => 'on',  
    '_modzzz_listing_yes' => 'yes',  
    '_modzzz_listing_no' => 'no',  
 
	'_modzzz_listing_package_videos' => 'Videos',  	
	'_modzzz_listing_package_photos' => 'Photos',  	
	'_modzzz_listing_package_sounds' => 'Sounds',  	
	'_modzzz_listing_package_files' => 'Files', 

	'_modzzz_listing_block_listing_states' => 'States', 
 
    '_mma_listing_purchase_featured' => 'listing purchase featured', 
    '_mma_listing_make_claim' => 'listing make claim', 
    '_mma_listing_make_inquiry' => 'listing make inquiry', 

    '_modzzz_listing_regions_for_country' => 'States/Regions for',  
	'_modzzz_listing_block_browse_state' => 'Browse States', 
	'_modzzz_listing_block_browse_state_listings' => 'Browse Listings by State', 
	'_modzzz_listing_block_account' => 'Listings in my Area',  
	'_modzzz_listing_block_browse_country' => 'Browse by Country', 
	'_modzzz_listing_page_title_local' => 'Browse Local Listings',  
	'_modzzz_listing_caption_browse_local' => 'Browse Local Listings in {0}', 
	'_modzzz_listing_menu_local' => 'Local', 
 	'_modzzz_listing_block_local' => 'More Local Listings',
	'_modzzz_listing_block_other' => 'Other Listings by this member',
 	'_modzzz_listing_caption_browse_other' => 'Other Listings by {0}',


	'_modzzz_listing_action_title_purchase_featured' => 'Get Featured',
	'_modzzz_listing_action_title_extend_featured' => 'Extend Featured',  
	'_modzzz_listing_purchase_featured_status' => 'Purchase Featured Status',  
	'_modzzz_listing_quantity' => 'Quantity',   
	'_modzzz_listing_purchase_success' => 'You successfully Purchased {0} Days of Featured Status', 
	'_modzzz_listing_purchase_fail' => 'Your attempt to Purchase Featured Status has failed',  
	'_modzzz_listing_purchase_failed' => 'Your attempt to Purchase Featured Status has failed',  
	'_modzzz_listing_transaction_completed_already' => 'This transaction was already completed',  
	'_modzzz_listing_featured_cost_per_day' => 'Cost per Day',  
	'_modzzz_listing_caption_num_featured_days' => 'Number of Featured Days',    
	'_modzzz_listing_caption_err_featured_days' => 'You must enter Number of Featured Days',    
	'_modzzz_listing_get_featured' => 'Get Featured',  
 

    '_modzzz_listing_parent_categories' => 'Parent', 
    '_modzzz_listing_block_category_listing' => 'Listings in this Category',
    '_modzzz_listing_block_subcategories' => 'Sub-Categories',  
    '_modzzz_listing_manage_subcategories_msg' => 'To manage Sub-Categories, go to Parent Categories and select the Category of interest. Then click the Sub-Categories button', 
	'_modzzz_listing_categ_name' => 'Category',
	'_modzzz_listing_categ_btn_edit' => 'Edit',
	'_modzzz_listing_categ_btn_delete' => 'Delete',
	'_modzzz_listing_categ_btn_add' => 'Add',
	'_modzzz_listing_categ_btn_save' => 'Save',
	'_modzzz_listing_categ_btn_subcategories' => 'Sub-Categories', 
 	'_modzzz_listing_categories' => 'Categories',
 	'_modzzz_listing_menu_admin_manage_categories' => 'Categories',
  	'_modzzz_listing_menu_admin_manage_subcategories' => 'Sub-Cats',
  	'_modzzz_listing_subcategories' => 'Sub-Categories',
  	'_modzzz_listing_categories' => 'Categories',
    '_modzzz_listing_parent_categories' => 'Parent Categories',
    '_modzzz_listing_all_categories' => 'All Categories',
    '_modzzz_listing_block_categories' => 'Categories',
    '_modzzz_listing_block_categories' => 'Categories',
    '_modzzz_listing_block_listing_subcategories' => 'Sub-Categories',
    '_modzzz_listing_block_answer_categories' => 'Listing Categories',
    '_modzzz_listing_menu_categories' => 'Categories',
    '_modzzz_listing_page_title_browse_by_category' => 'Browse Listings By Category: ',
    '_modzzz_listing_form_caption_category' => 'Category',
    '_modzzz_listing_form_err_category' => 'Category is invalid', 
	'_modzzz_listing_page_title_category' => 'Category', 
    '_modzzz_listing_page_title_categories' => 'Listings Categories',
    '_modzzz_listing_page_title_subcategories' => 'Listings Sub-Categories', 
    '_modzzz_listing_listings_in_category' => '<b>Listings</b> in <b>%s</b>',  
    '_modzzz_listing_block_listing' => 'Listings', 
    
	'_modzzz_listing_packages' => 'Packages',
	'_modzzz_listing_package_name' => 'Package Name',
	'_modzzz_listing_package_price' => 'Package Price',
	'_modzzz_listing_package_days' => 'Package Days',
	'_modzzz_listing_form_caption_package' => 'Business Package',
	'_modzzz_listing_form_err_package' => 'Please select a Business Package',  
	'_modzzz_listing_purchaser' => 'Purchaser', 
	'_modzzz_listing_invoice_no' => 'Invoice #', 
	'_modzzz_listing_package' => 'Package', 
	'_modzzz_listing_invoice_date' => 'Invoice Date', 
	'_modzzz_listing_invoice_due_date' => 'Due Date', 
	'_modzzz_listing_status' => 'Status',
	'_modzzz_listing_pending' => 'Pending',
	'_modzzz_listing_paid' => 'Paid',
	'_modzzz_listing_active' => 'Active',
	'_modzzz_listing_inactive' => 'Inactive',
	'_modzzz_listing_approved' => 'Approved',
	'_modzzz_listing_expired' => 'Expired', 
	'_modzzz_listing_block_submenu_pending_invoices' => 'Pending Invoices',
	'_modzzz_listing_block_submenu_orders' => 'Orders',
	'_modzzz_listing_page_title_orders' => 'Orders', 
	'_modzzz_listing_page_title_invoices' => 'Invoices', 
	'_modzzz_listing_menu_manage_invoices' => 'Invoices', 
	'_modzzz_listing_menu_manage_packages' => 'Packages',
	'_modzzz_listing_menu_manage_orders' => 'Orders',
	'_modzzz_listing_payment_method' => 'Payment Method',
	'_modzzz_listing_total' => 'Total',
	'_modzzz_listing_invoice_id' => 'Invoice ID',
	'_modzzz_listing_next_due_date' => 'Next Due Date',
	'_modzzz_listing_order_no' => 'Order #',
	 '_modzzz_listing_product_status' => 'Product Status',
	'_modzzz_listing_order_date' => 'Order Date',
	'_modzzz_listing_purchase_failed' => 'Sorry, there was a problem with the Payment.  View your Pending Orders <a href="{0}">here</a>.',
	'_modzzz_listing_transaction_completed_already' => 'The Transaction exists already. Click <a href="{0}">here</a> to view the Listing.',
	'_modzzz_listing_purchase_success' => 'Thank you. The Payment was successful. Click <a href="{0}">here</a> to view the Listing.',  
	'_modzzz_listing_trans_save_failed' => 'The Payment was successful but there was a Problem saving the transaction. Please contact the administrator with your Paypal transaction details so they can manually process your Order. View your Pending Orders <a href="{0}">here</a>',
	'_modzzz_listing_post_purchase_header' => 'Business Listing Purchase',  
 

	'_modzzz_listing_caption_state' => 'State',  
	'_modzzz_listing_regions_for_country' => 'States/Regions for',  
	'_modzzz_listing_block_browse_state' => 'Browse States', 
	'_modzzz_listing_block_browse_state_events' => 'Browse Listings by State',
	'_modzzz_listing_block_browse_country' => 'Browse by Country', 
	'_modzzz_listing_page_title_local' => 'Browse Local Listings',  
	'_modzzz_listing_caption_browse_local' => 'Browse Local Listings in {0}', 
	'_modzzz_listing_menu_local' => 'Local',
 	'_modzzz_listing_caption_search' => 'Search Business Listings',
 

    '_modzzz_listing_no_listings' => 'There are no Listings',
    '_sbs_txt_title_modzzz_listing' => 'Listings',
    '_modzzz_listing' => 'Listing',
    '_modzzz_listing_fans' => 'fans',
    '_modzzz_listing_add' => 'add',
    '_modzzz_listing_wall_added_new' => 'added new',
    '_modzzz_listing_wall_object' => 'business listing',
    '_modzzz_listing_for_listing' => 'for %s',
    '_modzzz_listing_listing_single' => 'business listing',
    '_modzzz_listing_listing_plural' => 'business listings',
    '_modzzz_listing_user_unknown' => 'Unknown',
    '_modzzz_listing_disabled' => 'disabled',
    '_modzzz_listing_enabled' => 'enabled',
    '_modzzz_listing_cannot_delete_default_parent' => 'Cannot Delete Default Parent Category',
	  
    '_modzzz_listing_edit' => 'Edit Listing Location',
    '_modzzz_listing_box_footer_edit' => 'Edit location',
    '_modzzz_listing_current_location' => 'Current Location:',
    '_modzzz_listing_privacy_view_location' => 'Allow viewing location to',
    '_modzzz_listing_privacy_update_ok' => 'Privacy setting has been successfully updated',
    '_modzzz_listing_privacy_update_fail' => 'Error occurred',
    '_modzzz_listing_the_same_address' => 'the same as primary address',  
    '_modzzz_listing_msg_locations_is_not_defined' => 'Your location is not defined',
    '_modzzz_listing_msg_incorrect_google_key' => 'Your Google API key is invalid or your browser is incompatible with Google Maps', 
	'_modzzz_listing_title_block_edit_location' => 'Edit Location',  
	'_modzzz_listing_title_block_edit_location_info' => 'Location Info',   
	'_modzzz_listing_unknown_city' => 'Unknown',  
	'_modzzz_listing_current_location' => 'Current Location', 
    '_modzzz_listing_block_map' => 'Map',
    '_modzzz_listing_admin_links' => 'Links',
    '_modzzz_listing_admin_update_profiles' => 'Update listings',
    '_modzzz_listing_admin_update_cities' => 'Update cities',
    '_modzzz_listing_admin_links_explanation' => 'You can get your google API key for your domain here:<br /><a href="http://code.google.com/apis/maps/signup.html">http://code.google.com/apis/maps/signup.html</a> <br /><br />You need to update all listings locations if you have installed this mod after creating any listings. Please update listings locations first, and after completion you can update cities.', 
  


    '_modzzz_listing_spy_post' => '<a href="{profile_link}">{profile_nick}</a> added new business listing <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_listing_spy_post_change' => '<a href="{profile_link}">{profile_nick}</a> changed business listing <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_listing_spy_rate' => '<a href="{profile_link}">{profile_nick}</a> rated business listing <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_listing_spy_comment' => '<a href="{profile_link}">{profile_nick}</a> commented business listing <a href="{entry_url}">{entry_title}</a>',

    '_modzzz_listing_sbs_change' => 'information was updated',
    '_modzzz_listing_sbs_comment' => 'new comment arrived',
    '_modzzz_listing_sbs_rate' => 'rating was updated',
 
    '_modzzz_listing_tab_featured' => 'Featured',
    '_modzzz_listing_tab_recent' => 'Recent',
    '_modzzz_listing_tab_top' => 'Top',
    '_modzzz_listing_tab_popular' => 'Popular',

    '_modzzz_listing_block_submenu_main' => 'Main',
    '_modzzz_listing_block_submenu_add_listing' => 'Add',
    '_modzzz_listing_block_submenu_manage_listing' => 'Manage',
    '_modzzz_listing_block_submenu_pending_listing' => 'Pending Approval',

    '_modzzz_listing_block_actions' => 'Actions',
    '_modzzz_listing_block_rate' => 'Rate',    
    '_modzzz_listing_block_info' => 'Info',
    '_modzzz_listing_block_desc' => 'Description',
    '_modzzz_listing_block_photo' => 'Photos',
    '_modzzz_listing_block_video' => 'Videos',
    '_modzzz_listing_block_sound' => 'Sounds',
    '_modzzz_listing_block_files' => 'Files',
    '_modzzz_listing_block_file' => 'Files',
    '_modzzz_listing_block_comments' => 'Comments',
    '_modzzz_listing_block_latest_featured_listing' => 'Latest Featured Listings',
    '_modzzz_listing_block_recent' => 'Recent Listings',
    '_modzzz_listing_block_popular' => 'Popular Listings',
    '_modzzz_listing_block_top' => 'Top Rated Listings',
    '_modzzz_listing_block_search' => 'Search Listings',
    '_modzzz_listing_block_listing_categories' => 'Business Categories',

    '_modzzz_listing_block_administration_owner' => 'Administration',
    '_modzzz_listing_block_users_listing' => "User Listings",
    '_modzzz_listing_block_my_listing' => 'My Listing',
    '_modzzz_listing_block_my_listings' => 'My Listings',
    '_modzzz_listing_block_area_listings' => 'Listings in my Area',

    '_modzzz_listing_block_homepage' => 'Business Listings',

    '_modzzz_listing_caption_add' => 'Add Listing',
    '_modzzz_listing_caption_share_listing' => 'Share Listing',
    '_modzzz_listing_caption_admin_actions' => 'Links',
    '_modzzz_listing_caption_pending_approval' => 'Pending Approval Listings', 
    
	'_modzzz_listing_menu_manage_parents' => 'Parent Cats',
    '_modzzz_listing_menu_manage_categories' => 'Cats',
    '_modzzz_listing_parent_categories' => 'Parent Categories',
    '_modzzz_listing_categ_btn_save' => 'Save',
    '_modzzz_listing_categ_btn_edit' => 'Edit',
    '_modzzz_listing_categ_btn_delete' => 'Delete',
    '_modzzz_listing_categ_name' => 'Name',
    '_modzzz_listing_categ_icon' => 'Icon',
    '_modzzz_listing_categ_present_icon' => 'Present Icon',
    '_modzzz_listing_categ_btn_add' => 'Add',

    '_modzzz_listing_menu_root' => 'Business Listings',
    '_modzzz_listing_menu_main' => 'Listings Home',
    '_modzzz_listing_menu_recent' => 'Recent',
    '_modzzz_listing_menu_top_rated' => 'Top Rated',
    '_modzzz_listing_menu_popular' => 'Popular',
    '_modzzz_listing_menu_featured' => 'Featured',
    '_modzzz_listing_menu_tags' => 'Tags',
    '_modzzz_listing_menu_categories' => 'Categories',
    '_modzzz_listing_menu_calendar' => 'Calendar',
    '_modzzz_listing_menu_search' => 'Search',
    '_modzzz_listing_menu_view_listing' => 'Main',
    '_modzzz_listing_menu_view_comments' => 'Comments',
    '_modzzz_listing_menu_view_photos' => 'Photos',
    '_modzzz_listing_menu_view_videos' => 'Videos',
    '_modzzz_listing_menu_view_sounds' => 'Sounds',
    '_modzzz_listing_menu_view_files' => 'Files',
    '_modzzz_listing_menu_my_listing_profile' => 'Listings',

    '_modzzz_listing_menu_admin_pending_approval' => 'Pending',
    '_modzzz_listing_menu_admin_entries' => 'Admin Listings',
    '_modzzz_listing_menu_admin_add_entry' => 'Add',
    '_modzzz_listing_menu_admin_settings' => 'Settings',
    
    '_modzzz_listing_page_title_home' => 'Listing Home',
    '_modzzz_listing_page_title_calendar' => 'Listing Calendar',
    '_modzzz_listing_page_title_comments' => 'Comments',
    '_modzzz_listing_page_title_photos' => 'Photos',
    '_modzzz_listing_page_title_videos' => 'Videos',
    '_modzzz_listing_page_title_sounds' => 'Sounds',
    '_modzzz_listing_page_title_files' => 'Files',
    '_modzzz_listing_page_title_my_listing' => 'My Listings',
    '_modzzz_listing_page_title_search' => 'Business Search',
    '_modzzz_listing_page_title_add' => 'Add Listing', 
    '_modzzz_listing_page_title_edit' => 'Edit Listing',
    '_modzzz_listing_page_title_administration' => 'Listings Administration',
    '_modzzz_listing_page_title_browse' => 'Browse Listings',
    '_modzzz_listing_page_title_pending_approval' => 'Pending Approval Listings',
    '_modzzz_listing_page_title_search_results' => 'Listing Search Results',
    '_modzzz_listing_page_title_browse_by_author' => "\'s listings",
    '_modzzz_listing_page_title_admin_listing' => 'Admin Listings',
    '_modzzz_listing_page_title_browse_by_category' => 'Browse Listings By Category: ',
    '_modzzz_listing_page_title_browse_by_tag' => 'Browse Listings By Tag: ',
    '_modzzz_listing_page_title_browse_recent' => 'Recent Listings',
    '_modzzz_listing_page_title_browse_top_rated' => 'Top Rated Listings',
    '_modzzz_listing_page_title_browse_popular' => 'Popular Listings',
    '_modzzz_listing_page_title_browse_featured' => 'Featured Listings',
    '_modzzz_listing_page_title_browse_by_day' => 'Browse Listings By Day: ',
    '_modzzz_listing_page_title_tags' => 'Listings Tags',
    '_modzzz_listing_page_title_categories' => 'Listings Categories',
    '_modzzz_listing_page_title_upload_photos' => 'Add Photos',
    '_modzzz_listing_page_title_upload_videos' => 'Add Videos',
    '_modzzz_listing_page_title_upload_sounds' => 'Add Sounds',
    '_modzzz_listing_page_title_upload_files' => 'Add Files',

    '_modzzz_listing_msg_pending_approval' => 'this listing is pending approval, please wait until it will be activated',
    '_modzzz_listing_msg_listing_was_deleted' => 'Listing was deleted',
    '_modzzz_listing_msg_removed_from_featured' => 'Listing was removed from featured',
    '_modzzz_listing_msg_added_to_featured' => 'Listing was added to featured',
    '_modzzz_listing_msg_photo_is_pending_approval' => 'Photo is pending approval',
    '_modzzz_listing_msg_you_have_pending_approval_listing' => 'You have <a href="%s">%d pending approval listings</a>',
    '_modzzz_listing_msg_you_have_no_listing' => 'You do not have any business listings. <a href="%s">Click here</a> to add one.',
    '_modzzz_listing_msg_you_have_some_listing' => 'You have <a href="%s">%d listing(s)</a>. <a href="%s">Click here</a> to add more.',

    '_modzzz_listing_admin_delete' => 'Delete',
    '_modzzz_listing_admin_activate' => 'Activate',
    '_modzzz_listing_admin_add_new_listing' => 'Add New Listing',
    '_modzzz_listing_admin_listing' => 'Admin Listing',
    '_modzzz_listing_admin_settings' => 'Admin Settings',

    '_modzzz_listing_form_header_info' => 'Listing Info',
    '_modzzz_listing_form_header_images' => 'Listing Photos',
    '_modzzz_listing_form_header_videos' => 'Listing Videos',
    '_modzzz_listing_form_header_sounds' => 'Listing Sounds',
    '_modzzz_listing_form_header_files' => 'Listing Files',
    '_modzzz_listing_form_header_privacy' => 'Privacy Settings',
    '_modzzz_listing_form_caption_title' => 'Title',
    '_modzzz_listing_form_err_title' => 'Please enter from 3 to 100 characters',
    '_modzzz_listing_form_caption_desc' => 'Description',
    '_modzzz_listing_form_err_desc' => 'Please enter at least 20 characters',
    '_modzzz_listing_form_err_tags' => 'Please enter tags',
    '_modzzz_listing_form_caption_author_id' => 'Author',
    '_modzzz_listing_form_info_author' => 'Author profile ID number',
    '_modzzz_listing_form_caption_keyword' => 'Keyword',
    '_modzzz_listing_form_err_keyword' => 'Please enter from 3 to 100 characters',
    '_modzzz_listing_form_caption_category' => 'Category',
    '_modzzz_listing_form_err_category' => 'Category is invalid',    
    '_modzzz_listing_form_caption_images_choice' => 'Choose',
    '_modzzz_listing_form_info_images_choice' => 'You can choose several images from your "Listing" category',
    '_modzzz_listing_form_caption_images_upload' => 'Upload',    
    '_modzzz_listing_form_info_images_upload' => 'Image will be placed in the "Listing" category automatically',
    '_modzzz_listing_form_caption_videos_choice' => 'Choose',
    '_modzzz_listing_form_info_videos_choice' => 'You can choose several videos from your "Listing" category',
    '_modzzz_listing_form_caption_videos_upload' => 'Upload',
    '_modzzz_listing_form_info_videos_upload' => 'Video will be placed in the "Listing" category automatically',
    '_modzzz_listing_form_caption_sounds_choice' => 'Choose',
    '_modzzz_listing_form_info_sounds_choice' => 'You can choose several sounds from your "Listing" category',
    '_modzzz_listing_form_caption_sounds_upload' => 'Upload',
    '_modzzz_listing_form_info_sounds_upload' => 'Sound will be placed in the "Listing" category automatically',
    '_modzzz_listing_form_caption_files_choice' => 'Choose',
    '_modzzz_listing_form_info_files_choice' => 'Unclick checkbox to remove file from this listing',
    '_modzzz_listing_form_caption_files_upload' => 'Upload',
    '_modzzz_listing_form_info_files_upload' => 'File will be placed in the "Listing" category and set as private automatically',
    '_modzzz_listing_form_caption_file_title' => 'Title:',
    '_modzzz_listing_form_caption_file_price' => 'Price:',
    '_modzzz_listing_form_caption_file_allow_purcase_to' => 'Allow purchase to:',
    '_modzzz_listing_form_caption_thumb_choice' => 'Choose thumbnail',
    '_modzzz_listing_form_info_thumb_choice' => 'You can choose any image from your "Listing" category as listing thumbnail',
    '_modzzz_listing_form_caption_country' => 'Country',
    '_modzzz_listing_form_err_country' => 'Country is a required field',
    '_modzzz_listing_form_caption_city' => 'City',
    '_modzzz_listing_form_err_city' => 'Please enter from 2 to 50 characters',
    '_modzzz_listing_form_caption_zip' => 'Zip/Postal Code',
    '_modzzz_listing_form_err_zip' => 'Zip/Postal code is required',
    '_modzzz_listing_form_err_email' => 'Invalid Email entered',

    '_modzzz_listing_action_title_edit' => 'Edit',
    '_modzzz_listing_action_title_delete' => 'Delete',
    '_modzzz_listing_action_title_share' => 'Share',
    '_modzzz_listing_action_add_to_featured' => 'Add To Featured',    
    '_modzzz_listing_action_remove_from_featured' => 'Remove From Featured',
    '_modzzz_listing_action_add_listing' => 'Add Listing',
    '_modzzz_listing_action_my_listing' => 'My Listing',
    '_modzzz_listing_action_upload_photos' => 'Add Photos',
    '_modzzz_listing_action_upload_videos' => 'Add Videos',
    '_modzzz_listing_action_upload_sounds' => 'Add Sounds',
    '_modzzz_listing_action_upload_files' => 'Add Files',
    '_modzzz_listing_action_listing_home' => 'Home',

    '_modzzz_listing_action_title_claim' => 'Claim Listing',
    '_modzzz_listing_action_title_inquire' => 'Inquire About', 
    '_modzzz_listing_action_title_spread' => 'Spread This', 
    '_modzzz_listing_action_title_promote' => 'Promote to Friends', 
    '_modzzz_listing_invitation_sent' => '%d Invitations have been sent',
	'_modzzz_listing_no_users_msg' => 'There are no users in your contacts',
	'_modzzz_listing_caption_invite' => 'Send Invitation To Friends - ',

    '_modzzz_listing_inquiry_subject' => 'Subject', 
    '_modzzz_listing_inquiry_subject_info' => 'Enter the Subject of your inquiry', 
    '_modzzz_listing_inquiry_text' => 'Message', 
    '_modzzz_listing_inquiry_text_info' => 'Enter your inquiry here. It will be forwarded to the Listing Owner',  
	'_modzzz_listing_caption_make_inquiry' => 'Make Inquiry - ',
    '_modzzz_listing_inquiry_sent' => 'your inquiry has been sent',
    '_modzzz_listing_inquiry_not_sent' => 'your inquiry has not been sent',
   
    '_modzzz_listing_claim_subject' => 'Subject', 
    '_modzzz_listing_claim_subject_info' => 'Enter the Subject of your claim', 
    '_modzzz_listing_claim_text' => 'Message', 
    '_modzzz_listing_claim_text_info' => 'Enter your proof of claim here. It will be forwarded to the Administrators',  
	'_modzzz_listing_caption_make_claim' => 'Make Claim - ',
    '_modzzz_listing_claim_sent' => 'your claim request has been sent',
    '_modzzz_listing_claim_not_sent' => 'your claim request has not been sent',
	 
	'_modzzz_listing_user_unknown' => 'Unknown', 
    '_modzzz_listing_price' => 'Price',

	'_modzzz_listing_business_contact' => 'Business Contact', 
	'_modzzz_listing_location' => 'Location',
	'_modzzz_listing_map' => 'Google Map', 
	'_modzzz_listing_form_caption_businessfax' => 'Business Fax',
	'_modzzz_listing_form_caption_businesstelephone' => 'Business Telephone',
	'_modzzz_listing_form_caption_businessemail' => 'Business Email',
	'_modzzz_listing_form_caption_businesswebsite' => 'Business Website',
	'_modzzz_listing_form_caption_businessname' => 'Business Name',
	'_modzzz_listing_form_caption_address1' => 'Address 1',
	'_modzzz_listing_form_caption_address2' => 'Address 2', 
	'_modzzz_listing_form_err_listingoption' => 'Please select an Option', 
	'_modzzz_listing_form_err_listingtype' => 'Please select a Type',
    '_modzzz_listing_form_err_city' => 'Please enter from 3 to 150 characters',
  
    '_modzzz_listing_privacy_view_listing' => 'View Listing',
    '_modzzz_listing_privacy_comment' => 'Comment',
    '_modzzz_listing_privacy_rate' => 'Rate',
    '_modzzz_listing_privacy_upload_photos' => 'Upload Photos',
    '_modzzz_listing_privacy_upload_videos' => 'Upload Videos',
    '_modzzz_listing_privacy_upload_sounds' => 'Upload Sounds',
    '_modzzz_listing_privacy_upload_files' => 'Upload Files',
    '_modzzz_listing_privacy_edit_listing' => 'Edit Listing',
    '_modzzz_listing_privacy_admins_only' => 'Admins Only',
    '_modzzz_listing_anonymous_note' => 'your name will not appear as the poster', 
    '_mma_listing_view_listing' => 'listing view listing', 
    '_mma_listing_browse' => 'listing browse', 
    '_mma_listing_search' => 'listing search', 
    '_mma_listing_add_listing' => 'listing add listing', 
    '_mma_listing_comments_delete_and_edit' => 'listing comments delete and edit', 
    '_mma_listing_edit_any_listing' => 'listing edit any listing', 
    '_mma_listing_delete_any_listing' => 'listing delete any listing', 
    '_mma_listing_mark_as_featured' => 'listing mark as featured', 
    '_mma_listing_approve_listing' => 'listing approve listing'   



);

?>
