<?
/***************************************************************************
* 
*     copyright            : (C) 2009 AQB Soft
*     website              : http://www.aqbsoft.com
*      
* IMPORTANT: This is a commercial product made by AQB Soft. It cannot be modified for other than personal usage.
* The "personal usage" means the product can be installed and set up for ONE domain name ONLY. 
* To be able to use this product for another domain names you have to order another copy of this product (license).
* 
* This product cannot be redistributed for free or a fee without written permission from AQB Soft.
* 
* This notice may not be removed from the source code.
* 
***************************************************************************/


$aLangContent = array(

    '_aqb_pc_title' => 'Profile Composer',
	'_aqb_pc_admin' => 'AQB Profile Composer',
	'_aqb_pc_administration' => 'AQB Profile Composer Administration',
	'_aqb_pc_block_title' => 'Blocks Management',
	'_aqb_pc_block_delete' => 'Delete',
	'_aqb_pc_block_approve' => 'Approve/Disapprove',
	'_aqb_pc_filter' => 'Filter',
	'_aqb_pc_filter_info' => 'Put here any symbols for filtration',
	'_aqb_pc_search_button' => 'Search',
	'_aqb_pc_filter_block_title' => 'block title',
	'_aqb_pc_filter_block_body' => 'block body',
	'_aqb_pc_filter_block_nickname' => 'owner\'s nickname',
	'_aqb_pc_filter_block_email' => 'owner\'s email',
    '_aqb_pc_filter_block_headline' => 'owner\'s headline', 
	'_aqb_pc_filter_block_tags' => 'owner\'s tags',
	'_aqb_pc_filter_block_type' => 'blocks\'s type',
	'_aqb_select_criteria' => 'Apply filtration using the next criteria',
	'_aqb_pc_admin_block_title' => 'title', 
	'_aqb_pc_admin_block_type' =>'type', 
	'_aqb_pc_admin_block_approved' => 'approved', 
	'_aqb_pc_admin_block_shared' =>'shared', 
	'_aqb_pc_admin_block_created' => 'created',
    '_aqb_pc_admin_username' => 'owner',
    '_aqb_pc_admin_last_login' => 'last login',
	'_aqb_pc_admin_actions' => 'actions',
	'_aqb_pc_admin_yes' => 'yes',
	'_aqb_pc_admin_no' => 'no',
	'_aqb_pc_admin_edit' => 'edit',
	'_aqb_pc_admin_view' => 'preview',
	'_aqb_pc_owner_nickname' => '{0}\'s block',
	'_aqb_pc_create_block' => 'create new block',
	'_aqb_block_type_text' => 'text',
	'_aqb_block_type_html' => 'html',
	'_aqb_block_type_rss' => 'rss',
	'_aqb_pc_block_title_edit' => 'Block title',
	'_aqb_pc_block_title_edit_info' => 'This info will be in the top of the block.<br/> Maximum allowed <b>100</b> symbols!',
	'_aqb_pc_block_body_edit' => 'Block content',
	'_aqb_pc_block_body_edit_info' => 'Here you may put any content you like,<br/> depends on the type of the block. Maximum allowed <b>{0}</b> symbols!',
	'_aqb_pc_block_types' => 'Available types of the blocks',
	'_aqb_pc_block_types_info' => 'You need to choose type of the block, which you want to create',
	'_aqb_pc_block_types_attrs' => 'Block parameters',
	'_aqb_pc_successfully_saved' => 'successfully saved',
	'_aqb_pc_have_to_login' => 'You need to login first',
		
	'_aqb_block_attrs_approved' => 'approved',
	'_aqb_block_attrs_share' =>  'can be shared',
	'_aqb_block_attrs_unmovable' => 'Fix block position',
	'_aqb_block_attrs_unmovable_addon' => '<br/>It has to be placed at',
	'_aqb_block_attrs_irremovable' => 'can not be removed from the page',
	'_aqb_block_attrs_collapsable' => 'can not be collapsed to the head',
	'_aqb_block_attrs_collapsable_def' => 'It will be collapsed by default on the member\'s profile',
	'_aqb_block_pos_top' => 'top',
	'_aqb_block_pos_bottom' => 'bottom',
	'_aqb_block_edit_column' => 'Column&nbsp;-&nbsp;',
	'_aqb_block_edit_position' => '&nbsp;position in the column - &nbsp;',
	'_aqb_pc_save_block' => 'Save',
	'_aqb_pc_place_block' => 'Place this block to all member\'s profiles',
	'_aqb_pc_error_body' => 'Body of the block can not be empty or exceeds {0} symbols!',
	'_aqb_pc_error_title' => 'Title of the block can not be empty or exceeds {0} symbols!',
	'_aqb_pc_create_new_block' => 'Create new block',
	'_aqb_pc_admin_settings' => 'Settings',
	'_aqb_pc_nothing_found' => 'Sorry, nothing found',
	'_aqb_pc_no_info' => 'No Info',
	
	'_aqb_pc_roll_up' => 'roll up',
	'_aqb_pc_unwrap' => 'unwrap',
	'_aqb_pc_change_block_privacy' => 'edit privacy',
	'_aqb_pc_avail_for_nonmembers' => 'make block available for non-members',
	'_aqb_pc_unavail_for_nonmembers' => 'make block unavailable for non-members',
	'_aqb_pc_edit_block_content' => 'edit',
	'_aqb_pc_share_block' => 'share block with other members',
	'_aqb_pc_unshare_block' => 'unshare block',
	'_aqb_pc_remove_block' => 'remove from my profile page',
	'_aqb_pc_request_remove_block' => 'ask admin to remove this block',
	'_aqb_pc_add_new_block' => 'Add my block',
	'_aqb_pc_block_title_edit' => 'Title',
    '_aqb_pc_block_title_edit_info' => 'Here you may put <b>Title</b> of the block', 	
	'_aqb_pc_block_body_edit' => 'Content',
	'_aqb_pc_advanced_block_body_edit_info' => 'Here you may put any <b>HTML</b> content',
	'_aqb_pc_save_button' => 'Save',
	'_aqb_create_blocks_is_not_allowed' => 'Sorry, Create blocks feature is not allowed!',
	'_aqb_pc_html_block' => 'HTML Block', 
	'_aqb_pc_text_block' => 'TEXT Block', 
	'_aqb_pc_rss_block' => 'RSS Block',
    '_aqb_pc_rss_block_body_edit_info' => 'Here you need to put rss link.<br/> <b>Example: http://www.boonex.com/unity/extensions/featured_posts?rss=1</b>',
	'_aqb_pc_text_block_body_edit_info' => 'Here you may put any text content. Maximum <b>{0}</b> symbols allowed.',
	'_aqb_pc_empty_fields' => 'Fields Title and Content can not be empty!',
	'_aqb_pc_blocks_limit_exceed' => 'Sorry, you blocks limit is exhausted!',
	'_aqb_pc_block_saved' => 'The block successfully saved',
	'_aqb_block_was_not_saved' => 'Sorry, block can not be saved!', 
	'_aqb_pc_profile_blocks' => 'Profile Blocks',
	'_aqb_pc_standard_blocks' => 'Standard site\'s blocks',
	'_aqb_pc_shared_blocks' => 'Shared member\'s blocks',
	'_aqb_pc_nothing_found' => 'Sorry, nothing found',
	'_aqb_pc_place_to_my_page' => 'place this block to my profile',
	'_aqb_pc_was_added_to_profile' => 'This block was successfully added to your profile!',
	'_aqb_pc_was_not_added_to_profile' => 'This block was not added by some reason!!! Please ask administration about it!',
	'_aqb_pc_blocks_owner' => 'Block owner {0}',
	'_aqb_pc_remove_block_from_site' => 'remove my block from the site',
	'_aqb_pc_remove_block_request_can_not_be_sent' => 'Sorry, request about removing this block can not be sent!',
	'_aqb_pc_remove_request_subject' => 'Member {0} ask to remove their block with title {1}',
	'_aqb_pc_remove_request_body' => 'Block ID is <b>{0}</b> <br/>Block title is <b>{1}</b>',
	'_aqb_pc_remove_block_request_sent' => 'Request about removing this block was successfully sent to administration of the site!',
	'_aqb_pc_can_not_be_removed_from_the_site' => 'Sorry, this block can not be removed from the site!',
	'_aqb_pc_has_been_successfully_removed_from_the_site' => 'Block was successfully removed from the site!',
	'_aqb_pc_admin_block_id' => 'id',
	'_aqb_pc_sorry_edit_not_allowed' => 'Sorry, block edit is not allowed!',
	'_aqb_pc_block_has_to_be_approved' => 'For security reasons this block must be approved before it appears on your page. To speed up this process please use the contact form to tell us that you have submitted a new block. Thanks for being part of the Community and using this advanced feature!', 
	'_aqb_block_was_not_updated' => 'Sorry, block was not updated!',
	'_aqb_pc_all_blocks' => 'all (<b>{0}</b>)',
	'_aqb_pc_approved_blocks' => 'only approved blocks (<b>{0}</b>)',
	'_aqb_pc_not_approved_blocks' => 'not approved blocks (<b>{0}</b>)',
	'_aqb_pc_profile_page' => 'Profile Builder',
	'_aqb_pc_apply_to_members_confirm' => 'Current blocks settings and blocks structure will be applied to all members profiles! Continue?',
	'_aqb_pc_apply_to_members' => 'Apply current settings to member\'s profiles',
	'_aqb_pc_structure_was_applied' => 'New settings were successfully applied to the all members profiles',
	'_aqb_pc_structure_was_not_applied' => 'Sorry, new settings was not applied! It seems to be you have problems with site database. Ask developer of the mod about it!',
	'_aqb_pcomposer_block_title' => 'Blocks management',
	'_aqb_pcomposer_admin' => 'Aqb Profile Composer',
	'_aqb_block_attrs_collapsible' => 'can not be collapsed to the head',
	'_aqb_points_action_aqb_pcomposer_edit' => 'block was changed', 
	'_aqb_points_action_aqb_pcomposer_add' => 'new block was added',
	'_aqb_points_action_aqb_pcomposer_remove' => 'a block was removed',
	'_aqb_points_action_aqb_pcomposer_approved' => 'your block was approved', 
	'_aqb_points_action_aqb_pcomposer_disapproved' => 'your block was disapproved',
	'_aqb_module_title_aqb_pcomposer' => 'AQB Profile Composer',
	'_aqb_pc_filter_block_id' => 'block id',
	'_aqb_pc_approve_blocks' => 'Manage Blocks',
	'_aqb_pc_you_are_not_groups_owner' => 'You are not a Group Owner!',
	'_aqb_pc_disapproved_blocks' => 'disapproved',
	'_aqb_pc_approved_blocks' => 'approved',
	'_aqb_pc_admin_block_manage_title' => 'Title',
	'_aqb_pc_admin_block_manage_created' => 'Creation Date',
	'_aqb_pc_admin_manage_username' => 'Blocks\'s Owner',
	'_aqb_pc_block_manage_approve' => 'Approve',
	'_aqb_pc_block_manage_disapprove' => 'Disapprove'
	
);

?>