var ig_a=false,ig_=null,ig_b=true;function ig_c(a,b){var c=function(){};c.prototype=a.prototype;b.prototype=new c}function _gel(a){return document.getElementById?document.getElementById(a):ig_}function _gelstn(a){if(a=="*"&&document.all)return document.all;return document.getElementsByTagName?document.getElementsByTagName(a):[]}function _gelsbyregex(a,b){var c=_gelstn(a),d=[];for(var e=0;e<c.length;e++)b.test(c[e].id)&&d.push(c[e]);return d}function _uc(a){return a.toUpperCase()}
function _trim(a){return a.replace(/^\s*|\s*$/g,"")}function _esc(a){return window.encodeURIComponent?encodeURIComponent(a):escape(a)}var ig_d=function(a){return window.decodeURIComponent?decodeURIComponent(a):unescape(a)},_unesc=ig_d;function _toggle(a){if(!a)return;if(a.style.display==""||a.style.display=="block")a.style.display="none";else if(a.style.display=="none")a.style.display="block"}
function _hesc(a){a=a.replace(/</g,"&lt;").replace(/>/g,"&gt;");a=a.replace(/"/g,"&quot;").replace(/'/g,"&#39;");return a}function _striptags(a){return a.replace(/<\/?[^>]+>/gi,"")}var ig_e=0;function _uid(){return"obj"+ig_e++}function _min(a,b){return a<b?a:b}function _max(a,b){return a>b?a:b}function _IG_LoadScript(a,b){_sendx(a,function(c){window.eval(c);eval(b)},ig_a,ig_)}
function _IG_LoadScriptXDomain(a,b,c){var d=document.createElement("script");d.src=a;document.getElementsByTagName("head")[0].appendChild(d);function e(f,g){eval(f)?g():setTimeout(function(){e(f,g)},100)}e(b,c)}
function _IG_LoadCss(a){var b=document.getElementsByTagName("head")[0];if(!b)throw new Error("Document is missing <head> element.  Failed to load CSS.");var c=document.createElement("style");c.type="text/css";if(c.styleSheet)c.styleSheet.cssText=a;else c.appendChild(document.createTextNode(a));b.insertBefore(c,b.firstChild)}function _log(a){var b="/ig/log?msg="+_esc(a);_sendx(b,ig_,ig_,ig_)}
function _sendx(a,b,c,d){var e=ig_f();e.open(d?"POST":"GET",a,ig_b);if(b)e.onreadystatechange=function(){if(e.readyState==4)b(c&&e.responseXML?e.responseXML:e.responseText)};e.send(d)}function _uhc(a,b,c){var d="m_"+a+"_"+b,e=_gel(d);if(!e){e=document.createElement("INPUT");e.type="hidden";e.disabled=ig_b;e.name=d;_gel("m_"+a+"_form").appendChild(e)}e.value=c;e.disabled=ig_a}
function ig_f(){var a=ig_;if(window.ActiveXObject){a=new ActiveXObject("Msxml2.XMLHTTP");a||(a=new ActiveXObject("Microsoft.XMLHTTP"))}else if(window.XMLHttpRequest)a=new XMLHttpRequest;return a}var _et="",_brand="",_bmod="",_source="",_ae="",_pid="",_authpath="",_prefid="",_setp_url="/ig/setp",_old_html=ig_b,_use_old_feed_styles=ig_b,ig_g=ig_,ig_h=ig_;function ig_i(a,b,c){var d=document.createElement("input");d.type="hidden";d.name=b;d.value=c;a.appendChild(d)}
function ig_j(a){var b=a||document.location.href,c,d=b.indexOf("?"),e=b.indexOf("#");c=e==-1?b.substr(d+1):b.substr(d+1,e-d-1)+"&"+b.substr(e+1);return c.split("&")}function _argsUrl(a){var b={},c=ig_j(a);for(var d=0;d<c.length;d++){var e=c[d].indexOf("=");if(e==-1)continue;var f=c[d].substring(0,e),g=c[d].substring(e+1);g=g.replace(/\+/g," ");b[f]=_unesc(g)}return b}function _args(){return _argsUrl(document.location.href)}
function _IG_isIE(){var a=navigator.userAgent.toLowerCase();return a.indexOf("msie")!=-1}function ig_k(a){var b={pid:1,host:1,gl:1,hl:1},c=a||_args(),d="?";for(var e in c)if(b[e])d+=e+"="+_esc(c[e])+"&";return d}function ig_l(a){var b={url:document.location,et:_et,brand:_brand,bmod:_bmod,source:_source,ae:_ae,pid:_pid,ap:_authpath,prefid:_prefid};for(var c in b)ig_i(a,c,b[c])}function _submit_form(a,b){a.action=_setp_url+ig_k()+b;a.method="get";ig_l(a);a.submit()}
function _fsetp(a,b,c){a.action=_setp_url;a.method="get";ig_l(a);ig_i(a,"m_"+b+"_t",c);var d=_args(),e=d.host,f=d.hl;typeof e!="undefined"&&ig_i(a,"host",e);typeof f!="undefined"&&ig_i(a,"hl",f);return ig_b}var ig_m=[],ig_n=ig_a;function ig_o(a){var b=[];for(var c=0;c<a.length;++c){if(a[c].length!=2)continue;var d=a[c][0],e=a[c][1];e!=ig_&&e!=""&&b.push(d+"="+e)}return b.join("&")}
function ig_p(){return ig_o([["et",_et],["pid",_pid],["ap",_authpath],["brand",_brand],["bmod",_bmod],["source",_source],["ae",_ae],["prefid",_prefid]])}function ig_q(){if(ig_m.length==0){ig_n=ig_a;return}ig_n=ig_b;var a=_setp_url+ig_k()+ig_p(),b=ig_m.shift(),c=a.length+b.length>=1800;if(c)_sendx(a,ig_r,ig_a,b);else{a+="&"+b;_sendx(a,ig_r,ig_a,ig_)}}function ig_r(){_IG_TriggerDelayedEvent("xsetpdone");ig_q()}function _xsetp(a){ig_m.push(a);ig_n||ig_q()}
function _dlsetp(a,b){b||(b=_esc(document.location));document.location=_setp_url+ig_k()+ig_p()+"&url="+b+"&"+a}function _removeTabParam(a){return a.replace(/(\?.*\b)(t\=[^&#]*[&#]?)/g,"$1")}function _select_tab(a,b){var c=b||"/ig";window.location.href=c+ig_k()+"t="+a}function _select_tab_and_log(a,b){_sendx("/ig/ui?xp=v2&action=selectTab&t="+a,ig_,ig_a,ig_);_select_tab(a,b)}
function _select_gadget_and_log(a,b){_sendx("/ig/ui?xp=v2&action=maximizeMod&from=selectMod&mid="+b,ig_,ig_a,ig_);window.location.href="/ig"+ig_k()+"t="+a+"&g="+b}function _ssbc(a,b,c){var d=_gelstn("*");for(var e=0;e<d.length;e++)if(d[e].className==a)d[e].style[b]=c}function ig_s(a){var b=_gelstn("*");for(var c=0;c<b.length;c++)for(var d=0;d<a.length;d++)if(b[c].className==a[d][0])b[c].style[a[d][1]]=a[d][2]}
function _findPos(a){var b=0,c=0;while(a!=ig_){b+=a.offsetLeft;c+=a.offsetTop;a=a.offsetParent}return[b,c]}function _getGadgetContainer(a){var b=_gel("m_"+a+"_b");if(!b){b=_gel("remote_"+a);if(!b)b=document.body}return b}function _appendMaxAgeParameter(a,b){var c=/[?&]$/.test(a);return a+(c?"":"&")+"max_age="+b+(c?"&":"")}
(function(){function a(d){var e=window;if(d!=""){var f=d.split(".");while(f.length){var g=f.shift();if(typeof e[g]!="object")e[g]={};e=e[g]}}return e}function b(d,e){var f=a(d);for(var g=0;g<e.length;g+=2)f[e[g]]=e[g+1]}function c(d,e,f,g,h){if(g)for(var j=0;j<g.length;j+=2)f.prototype[g[j]]=g[j+1];if(h)for(var j=0;j<h.length;j+=2)f[h[j]]=h[j+1];b(d,[e,f])}b("",["_exportSymbols",b]);b("",["_exportClass",c]);b("google.gadgets.Util",["args",_args])})();function _preloadImages(a,b){var c=a.length,d=[];for(var e=0;e<a.length;e++){var f=new Image;d.push(f);f.src=a[e];if(f.complete){c--;ig_t(c,b,d)}else f.onload=function(){c--;ig_t(c,b,d)}}}function ig_t(a,b,c){if(a==0){b&&b();for(var d=0;d<c.length;d++){c[d].onload=ig_;c[d]=ig_}}}function _edit(a,b){var c=ig_u[a];if(c)c();else _gel("m_"+a).className="modbox_e";b&&b();ig_v("edit","m_"+a);return ig_a}var ig_u={};function _IG_AddCustomEditHandler(a,b){ig_u[a]=b}
function _cedit(a){_gel("m_"+a).className="modbox";var b=_gel("m_"+a+"_form");b.reset();ig_v("canceledit","m_"+a);return ig_a}function _confirmDel(a,b,c,d){var e=_striptags(_gel("m_"+a+"_title").innerHTML);d=d.replace(/MODULE_TITLE/,'"'+e+'"');confirm(d)&&_del(a,b,c)}function _get_module_title(a){if(typeof a=="object")a=a.id.replace("m_","");else if(typeof a=="string")a=a.replace("m_","");var b=_gel("m_"+a+"_title");return b?_striptags(b.innerHTML):""}
function _get_all_modules(){var a=ig_w(),b=[],c=/^m_[0-9]+$/;for(var d=0;d<a.length;d++){b[d]=[];var e=b[d];for(var f=0;f<a[d].childNodes.length;f++){var g=a[d].childNodes[f];g.tagName=="DIV"&&g.style.display!="none"&&g.id&&c.test(g.id)&&e.push(g)}}if(window.gadgets&&window.gadgets.views&&window.gadgets.views.ViewManager&&window.gadgets.views.ViewManager.getCurrentMaxId){var h=window.gadgets.views.ViewManager.getCurrentMaxId();h&&b.length>0&&h&&b[0].unshift(_gel("m_"+h))}return b}
function ig_w(){var a=_gelsbyregex("DIV",/^c_[0-9]+$/),b=[];for(var c=0;c<a.length;c++)a[c].style.display!="none"&&b.push(a[c]);return b}var ig_x={},ig_y={};function _place(a,b){var c=ig_y[a];if(c){c(b);return}ig_x[a]||(ig_x[a]=[]);ig_x[a].push(b)}function _register_place(a,b){ig_y[a]=b;var c=ig_x[a];if(c){for(var d=0;d<c.length;d++)b(c[d]);ig_x[a]=ig_}}
function _del(a,b,c){_xsetp("m_"+a+"_enab=0&m_"+a+"_t="+b);var d=_gel("undel_msg");if(d){_gel("undel_title").innerHTML="&quot;"+_get_module_title(a)+"&quot; ";d.style.display="block";var e=_gel("undo_msg");if(e)e.style.display="none";e=_gel("undo_restore_msg");if(e)e.style.display="none"}var f=_gel("m_"+a);if(f)f.style.display="none";ig_g=a;ig_h=c;var g=_gel(c);if(g)g.style.display="";_mod=ig_b;ig_v("delete","m_"+a);return ig_a}
function _undel(){if(ig_g==ig_)return;var a="m_"+ig_g,b=_gel(a);if(b){b.style.display="block";_xsetp("undel")}var c=_gel("undel_msg");if(c)c.style.display="none";if(ig_h!=ig_){var d=_gel(ig_h);if(d)d.style.display="none"}ig_g=ig_;ig_h=ig_;ig_v("undelete",a)}
function _zm(a,b,c){var d=_gel("m_"+a+"_b");if(d){var e=d.style.display!="none";d.style.display=e?"none":"block";var f=_gel("m_"+a+"_zippy");if(f)f.className=e?f.className.replace(/minbox/,"maxbox"):f.className.replace(/maxbox/,"minbox");var g=c?"mmz":"mz";_xsetp(g+"="+a+":"+(e?"1":"0")+"&t="+b);ig_v(e?"zip":"unzip",a)}return ig_a}var ig_z="https://www.google.com/accounts";
function _enableGS(a,b){a.action=ig_z+"/CheckCookie";a.method="get";ig_i(a,"service",b);ig_i(a,"continue",document.location);ig_i(a,"skipvpage",ig_b);return ig_b}function _reload(a,b){var c=a-(new Date).getTime();if(c>1000){setTimeout("_reload("+a+")",c);return}if(b)document.location.replace(ig_aa(document.location.href,document.location.pathname));else{document.cookie="IGREL=1";document.location.replace(document.location.href)}}
function ig_aa(a,b){var c=a.split("?"),d=c[0];if(b=="/")d+="ig";d+="?";var e=c[1];if(e)d+=e;if(!_argsUrl(a).refresh){if(e)d+="&";d+="refresh=1"}return d}function ig_v(a,b){switch(a){case "delete":case "undelete":case "edit":case "canceledit":case "zip":case "unzip":case "mazimize":case "unmaximize":_IG_TriggerDelayedModuleEvent(b,a);_IG_TriggerDelayedEvent("module"+a,b);break}}function ig_ba(a){_xsetp("pnlo="+(a?1:0))}var _uli,_pnlo,_mpnlo,_pl,_mod,_cbp=ig_a,ig_A=ig_a,_table=ig_,_tabs=ig_;
function _upc(){var a=[];_cbp||(a[a.length]=["medit","display",_uli?"":"none"]);a[a.length]=["panelo","display",_pnlo?"":"none"];a[a.length]=["panelc","display",_pnlo?"none":""];if(_mod){a[a.length]=["unmod","display","none"];a[a.length]=["mod","display",""]}else{a[a.length]=["mod","display","none"];a[a.length]=["unmod","display",""]}ig_s(a);_init_drag_drop()}function _init_drag_drop(){if(_pl)if(_cbp||_uli)if(!ig_A&&!_mpnlo){_IG_TriggerCustomEvent("initdrag",_table,_tabs);ig_A=ig_b}}var ig_B=0;
function _tp(a){ig_B>0&&clearInterval(ig_B);_pnlo=a;_mod=ig_b;ig_ba(a);_upc();var b=_gel("cpnl"),c=_gel("cpnlc"),d=_gel("nhdr"),e=_gel("ehdr"),f=b.offsetWidth,g,h;if(a){g=c.offsetWidth;h="visible";e.style.display="";d.style.display="none"}else{g=1;h="hidden";e.style.display="none";d.style.display=""}b.style.overflow="hidden";var j=100,l=10,n=0;ig_B=setInterval(function(){var o=n/l,p=f+(g-f)*o;b.style.width=p+"px";n++;if(o>=1){clearInterval(ig_B);ig_B=0;b.style.width=g+"px";b.style.overflow=h}},j/
l);return ig_a}function _ts(a,b){var c=_gel(a+b),d;if(c.className=="mlist_open"){c.className="mlist_closed";d="pnlsc"}else{c.className="mlist_open";d="pnlso"}_xsetp(d+"="+_esc(b));return ig_a}function _add_m(a,b){_dlsetp(a,b)}function _add_m_confirm(a,b,c){confirm(b)&&_add_m(a,c)}function _add_f(a){_add_m("n_25="+_esc("url="+_esc(a)))}var ig_C=/^_add_m(_confirm)?\(\"[^"]+\"(, *\"[^"]+\")?\)$/;
function _find_feed(a){var b="acd";if(!a){var c=_gelstn("div");if(c)for(var d=0;d<c.length;d++)c[d].id&&c[d].id.indexOf("ps")==0&&c[d].className=="mlist_open"&&_ts("ps",c[d].id.substring(2));if(_gel("add_custom"))a=_gel("add_custom").value}if(!a||a==""){b="advdsrch";a=_gel("add_advd").value}var e=_gel("ffresults");if(e)e.style.display="none";var f=_gel("ffloading");if(f)f.style.display="block";_sendx("/ig/feeds"+ig_k()+"q="+_esc(a)+"&page="+_esc(b),ig_ca,ig_a,ig_);return ig_a}
function ig_ca(a){var b=_gel("ffloading");if(b)b.style.display="none";var c=_gel("ffresults");if(c)c.style.display="block";if(a.length>0&&a.charAt(0)=="<")c.innerHTML=a;else a.match(ig_C)!=ig_?eval(a):eval(a)}function _add_remote_module(a,b,c){_sendx("/ig/feeds"+ig_k()+"module=1&q="+_esc(a),function(d){b();ig_da(d,c)},ig_a,ig_);return ig_a}
function ig_da(a,b){var c=/_add_m_confirm\((\"[^"]+\"),\s*(\"[^"]+\")(,\s*\"[^"]+\")?\)/,d=/^alert\(\"[^"]+\"\)$/;if(a.match(ig_C)!=ig_||a.match(d)!=ig_){if(b)a=a.replace(c,"_add_m($1$3)");eval(a)}}
function _ListApp(a,b,c){this.items=a;this.deleted=[];this.item_constructor=b;this.module_id=c;this.app_name="m_"+c+"_App";this.display_area=_gel("m_"+c+"_disp");this.sort_on_refresh=ig_b;this.value_input_field=_gel("m_"+c+"_val");this.name_input_field=_gel("m_"+c+"_name");if(!this.name_input_field)this.name_input_field=this.value_input_field;if(this.name_input_field){this.default_name=this.name_input_field.value;this.default_value=this.value_input_field.value}this.prev_items=[].concat(this.items)}
_ListApp.prototype.reset=function(){this.items=[].concat(this.prev_items);this.deleted=[];this.refresh()};_ListApp.prototype.sort=function(a,b){return a.w(b)};
_ListApp.prototype.cb=function(){var a="";if(_old_html)a="<table cellspacing=0 cellpadding=0 border=0>";var b="",c=this.items;for(var d=0;d<c.length;d++)if(c[d]){a+=_old_html?"<tr><td nowrap><font size=-1>"+c[d].H()+'</font></td><td><a href="#" onclick="'+this.app_name+"._del("+d+')"><img src="/ig/images/x.gif" width=16 height=13 border=0></a></td></tr>':'<a href="#" onclick="'+this.app_name+"._del("+d+')" class="delbox listdelbox"></a>'+c[d].H()+"<br>";if(parseInt(c[d]._uid,10)<0)b+=c[d].p(d)}else{this.items.splice(d,
1);d--}var e=this.deleted,f="";for(var d=0;d<e.length;d++)if(parseInt(e[d]._uid,10)>=0)f+=","+e[d]._uid;a+=this.ra(b,f);return a};_ListApp.prototype.ra=function(a,b){var c="<input type=hidden name=m_"+this.module_id+'_del value="'+b+'"><input type=hidden name=m_'+this.module_id+'_add value="'+a+'">';if(_old_html)c="</table><input type=hidden name=m_"+this.module_id+'_del value="'+b+'"><input type=hidden name=m_'+this.module_id+'_add value="'+a+'">';return c};
_ListApp.prototype.refresh=function(){this.sort_on_refresh&&this.items.sort(this.sort);this.display_area.innerHTML="<font size=-1>"+this.cb()+"</font>"};_ListApp.prototype.add=function(a,b){a||(a=_trim(this.name_input_field.value));b||(b=_trim(this.value_input_field.value));var c=new this.item_constructor(a,b,-1);if(!c.C())return;this.items[this.items.length]=c;this.refresh();this.name_input_field.value=this.default_name;this.value_input_field.value=this.default_value};
_ListApp.prototype._del=function(a){this.deleted[this.deleted.length]=this.items[a];this.items.splice(a,1);this.refresh()};
function _PrefListApp(a,b,c,d,e){var f=typeof c=="string"?[]:c,g=new _ListApp(f,d,e);for(var h in g)this[h]=g[h];typeof c=="string"&&this.bb(c);this.prefidx=a;this.prefname=b;this.app_name="m_"+e+"_"+a+"_App";this.display_area=_gel("m_"+e+"_"+a+"_disp");this.value_input_field=_gel("m_"+e+"_"+a+"_val");this.name_input_field=this.value_input_field;this.default_name="";this.default_value="";this.ra=_PrefListApp_get_tail}
function _PrefListApp_get_tail(){var a="</table>";_gel("m_"+this.module_id+"_"+this.prefidx).value=this.fb();return a}_PrefListApp.prototype.bb=function(a){if(a.length==0)return;var b=_IG_Prefs._strToArray(a),c=[];for(var d=0;d<b.length;d++){var e=new this.item_constructor(b[d],b[d],-1);c[c.length]=e}this.items=c;this.prev_items=[].concat(c)};_PrefListApp.prototype.fb=function(){var a=[];for(var b=0;b<this.items.length;b++)a[a.length]=this.items[b]._v;return _IG_Prefs._arrayToStr(a)};
function _ListItem(a,b,c){this._n=a;this._v=b;this._uid=c}_ListItem.prototype.C=function(){return this._n!=""};_ListItem.prototype.w=function(){return 0};_ListItem.prototype.H=function(){return _hesc(this._n)};_ListItem.prototype.p=function(){return"&"+_esc(this._n)+"="+_esc(this._v)};function _BMListItem(a,b,c){_ListItem.call(this,a,b,c)}ig_c(_ListItem,_BMListItem);_BMListItem.prototype.C=function(){return _ListItem.prototype.C.call(this)&&this._n!="http://"};
_BMListItem.prototype.N=function(){if(this._v)return this._v;else{var a=this._n;if(a.indexOf("http://")==0)a=a.substring(7);if(a.indexOf("www.")==0)a=a.substring(4);return a}};_BMListItem.prototype.H=function(){return'<a href="'+this._n+'" target=bmwindow>'+_hesc(this.N())+"</a>"};_BMListItem.prototype.p=function(a){return"&b"+a+"="+_esc(this._n)+"&t"+a+"="+_esc(this._v)};_BMListItem.prototype.w=function(a){var b=_uc(this.N()),c=_uc(a.N());if(b==c)return 0;return b<c?-1:1};
function _WthrListItem(a,b,c){_ListItem.call(this,a,b,c)}ig_c(_ListItem,_WthrListItem);_WthrListItem.prototype.p=function(){var a="&"+_esc(this._n);if(this._v)a+="="+_esc(this._v);return a};function _FListItem(a,b,c,d){_ListItem.call(this,a,b,c);this._s=d||0}ig_c(_ListItem,_FListItem);_FListItem.prototype.p=function(){return"&"+_esc(this._n)};_FListItem.prototype.w=function(a){var b=this;if(b._s<a._s)return-1;if(b._s>a._s)return 1;var c=_uc(b._n),d=_uc(a._n);if(c<d)return-1;if(c>d)return 1;return 0};
var ig_D={ha:0,gb:1800,xa:ig_,wa:ig_,Oa:ig_b,R:ig_,use_url_param_refresh:ig_,T:function(){ig_D.ha=(new Date).getTime()+ig_D.gb*1000},Kb:function(){(new Date).getTime()>ig_D.ha&&_testConnection(function(){_reload(ig_D.ha,ig_D.use_url_param_refresh)},ig_D.T)},za:function(a){ig_D.T();ig_D.xa&&ig_D.xa(a)},ya:function(a){ig_D.T();ig_D.wa&&ig_D.wa(a)}};function _IG_disable_refresh_cycle(){ig_D.Oa=ig_a;if(ig_D.R!=ig_){clearInterval(ig_D.R);ig_D.R=ig_}}
function _IG_start_refresh_cycle(a,b,c){if(ig_D.Oa){ig_D.xa=document.onmousedown;ig_D.wa=document.onkeyup;ig_D.gb=a;if(c)ig_D.use_url_param_refresh=c;if(document.addEventListener){document.addEventListener("keyup",ig_D.ya,ig_a);document.addEventListener("mousedown",ig_D.za,ig_a)}else if(document.attachEvent){document.attachEvent("onkeyup",ig_D.ya);document.attachEvent("onmousedown",ig_D.za)}else{document.onkeyup=ig_D.ya;document.onmousedown=ig_D.za}ig_D.T();ig_D.R=setInterval(ig_D.Kb,b*1000)}}
function _testConnection(a,b,c){var d=ig_f(),e="/ig/nop?t="+(new Date).getTime();c||(c=3500);d.open("GET",e,ig_b);d.onreadystatechange=function(){if(d.readyState==4&&a)if(200<=d.status&&d.status<300||d.status==1223){b=ig_;a()}};try{d.send(ig_)}catch(f){}var g=function(){if(b){a=ig_;b()}};setTimeout(g,c)}function _mailWindow(a){window.open(a,"mailwindow","width=400,height=340,left=50,top=50,scrollbars=no")}
function ig_E(a){if(!a)a=document.body;return a.scrollHeight>a.offsetHeight?a.scrollHeight:a.offsetHeight}function _setHomepage(a,b){var c=_gel("hp_url").innerHTML;a.style.behavior="url(#default#homepage)";a.setHomePage(c);_sendx("/ig/ui?action=sethomepage&url="+_esc(c)+"&type="+b+"&confirmed="+(_IGoogleIsHomepage()?1:0),ig_,ig_a,ig_)}function _IGoogleIsHomepage(){var a=_gel("shp"),b=_gel("hp_url").innerHTML;return a.isHomePage(b)}
function _maybeShowSetHPMsg(){if(!_IGoogleIsHomepage()){_gel("set_homepage_msg").style.display="inline";if(_gel("new_user_demo")!=ig_)_gel("new_user_demo").style.display="none"}}function _hideSetHPMsg(){if(_gel("set_homepage_msg")!=ig_)_gel("set_homepage_msg").style.display="none";if(_gel("new_user_demo")!=ig_)_gel("new_user_demo").style.display="block"}
function _iGoogleRejectedAsHomepage(){if(_gel("set_homepage_msg")!=ig_)_gel("set_homepage_msg").style.display="none";if(_gel("new_user_demo")!=ig_)_gel("new_user_demo").style.display="block";if(_gel("set_homepage_footer")!=ig_)_gel("set_homepage_footer").style.display="inline"}function _maybeShowSetHPFooter(){if(!_IGoogleIsHomepage()&&_gel("set_homepage_msg")==ig_)_gel("set_homepage_footer").style.display="inline"};function _IG_GetCachedUrl(a,b){var c;c=typeof b=="object"?b:{};var d=window.location.href,e="/ig/proxy?",f=/^http:\/\/[^\/]+\/ig\/ifr[?]/,g=f.exec(d);if(g||d.indexOf("http://www.google.cn/ig/china")==0){if(window.location.host!="p.gmodules.com"&&_et)e+="et="+_esc(_et)+"&"}else e="http://p.gmodules.com/ig/proxy?";if(!isNaN(c.refreshInterval)&&c.refreshInterval>=0)e=_appendMaxAgeParameter(e,c.refreshInterval);return e+"url="+_esc(a)+"&log=1"}
function _IG_GetImageUrl(a,b){return _IG_GetCachedUrl(a,b)}function _IG_GetImage(a,b){var c=document.createElement("img");c.src=_IG_GetCachedUrl(a,b);return c};function _IG_Callback(a){var b=arguments;return function(){var c=[];for(var d=0;d<arguments.length;d++)c[c.length]=arguments[d];for(var d=1;d<b.length;d++)c[c.length]=b[d];a.apply(ig_,c)}};var _IG_time=(function(){function a(){return(new Date).getTime()}var b=window._IG_time_epoch||a(),c={},d={},e={set_epoch:function(f){b=f},start:function(f){c[f]=a();e.start_callback(f)},since:function(f){var g=c[f]||b;return a()-g},stop:function(f){d[f]=e.since(f);e.stop_callback(f)},get:function(f){return d[f]},print:function(f){document.write("<div style='color:#999999;font-size:75%'>"+f+" : "+e.get(f)+"ms</div>")},stop_and_print:function(f){e.stop(f);e.print(f)},start_callback:function(){},stop_callback:function(){}};
return e})();var ig_ea={domload:1,xsetpdone:1,moduledragstart:1,moduledragend:1,moduletitleclick:1,moduleedit:1,modulecanceledit:1,moduledelete:1,moduleundelete:1,modulezip:1,moduleunzip:1,modulemaximize:1,moduleunmaximize:1,load:1,unload:1,resize:1},ig_fa={dragstart:1,dragend:1,titleclick:1,edit:1,canceledit:1,"delete":1,undelete:1,zip:1,unzip:1,maximize:1,unmaximize:1};function ig_ga(a){var b="ig_event_hashcode_";if(a.hasOwnProperty&&a.hasOwnProperty(b))return a[b];a[b]||(a[b]=++ig_F.Fb);return a[b]}
function ig_ha(a){return"builtin_"+a}function ig_ia(a,b){if(a.indexOf&&a.indexOf("m_")==0)a=a.substring(2);return"builtin_m"+a+"_"+b}function ig_ja(a,b){return"builtin_"+ig_F.Bb(a)+"_"+b}function ig_ka(a){return"custom_"+a}function ig_la(){for(var a in ig_F.c){for(var b=0;b<ig_F.c[a].length;b++)ig_F.c[a][b]=ig_;if(a in ig_F.M){var c=ig_F.M[a],d=c[0],e=c[1],f=c[2];if(d.removeEventListener)d.removeEventListener(e,f,ig_a);else d.detachEvent&&d.detachEvent("on"+e,f);ig_F.M[a]=ig_}}}
function ig_ma(a,b,c){for(var d=c;d<b.length;d++)a[a.length]=b[d];return a}function ig_na(a,b){if(a in ig_F.c)for(var c=0;c<ig_F.c[a].length;c++)if(ig_F.c[a][c]===b){ig_F.c[a][c]=ig_;return ig_b}return ig_a}function ig_oa(a){if(a in ig_F.c)for(var b=0;b<ig_F.c[a].length;b++)if(ig_F.c[a][b]){var c=[];for(var d=1;d<arguments.length;d++)c[c.length]=arguments[d];ig_F.c[a][b].apply(this,c)}}
function ig_pa(a,b){if(!(a in ig_F.Qb))throw Error("Unsupported event type: "+a);var c=ig_F.aa(a);c in ig_F.c||(ig_F.c[c]=[]);ig_F.c[c][ig_F.c[c].length]=b}function ig_qa(a,b,c){if(!(b in ig_F.Rb))throw Error("Unsupported module event type: "+b);var d=ig_F.ba(a,b);d in ig_F.c||(ig_F.c[d]=[]);ig_F.c[d][ig_F.c[d].length]=c}
function ig_ra(a,b,c){var d=ig_F.Sa(a,b);if(!(d in ig_F.c)){ig_F.c[d]=[];var e=function(g){if(!g)g=window.event;ig_F.U.apply(a,[d,g])};if(a.addEventListener)a.addEventListener(b,e,ig_a);else if(a.attachEvent)a.attachEvent("on"+b,e);else throw Error("Object {"+a+"} does not support DOM events.");ig_F.M[d]=[a,b,e]}var f=ig_F.c[d].length;if(a===window&&b=="unload"&&f>0){ig_F.c[d][f]=ig_F.c[d][f-1];ig_F.c[d][f-1]=c}else ig_F.c[d][f]=c}
function ig_sa(a,b){var c=ig_F.$(a);c in ig_F.c||(ig_F.c[c]=[]);ig_F.c[c][ig_F.c[c].length]=b}function ig_ta(a,b){var c=ig_F.aa(a);return ig_F.S(c,b)}function ig_ua(a,b,c){var d=ig_F.ba(a,b);return ig_F.S(d,c)}function ig_va(a,b,c){var d=ig_F.Sa(a,b);return ig_F.S(d,c)}function ig_wa(a,b){var c=ig_F.$(a);return ig_F.S(c,b)}function ig_xa(a){var b=a=="load"||a=="domload";b&&_IG_time.stop("pre_"+a);var c=ig_F.D([ig_F.aa(a)],arguments,1);ig_F.U.apply(window,c);b&&_IG_time.stop("post_"+a)}
function ig_ya(){var a=ig_F.D([],arguments,0);setTimeout(function(){ig_F.triggerEvent.apply(window,a)},0)}function ig_za(a,b){var c=ig_F.D([ig_F.ba(a,b)],arguments,2);ig_F.U.apply(window,c)}function ig_Aa(){var a=ig_F.D([],arguments,0);setTimeout(function(){ig_F.triggerModuleEvent.apply(window,a)},0)}function ig_Ba(a){var b=ig_F.D([ig_F.$(a)],arguments,1);ig_F.U.apply(window,b)}function ig_Ca(){var a=ig_F.D([],arguments,0);setTimeout(function(){ig_F.triggerCustomEvent.apply(window,a)},0)}
var ig_F={Fb:0,c:{},M:{},Qb:ig_ea,Rb:ig_fa,Bb:ig_ga,aa:ig_ha,ba:ig_ia,Sa:ig_ja,$:ig_ka,tb:ig_la,D:ig_ma,S:ig_na,U:ig_oa,addEventHandler:ig_pa,addModuleEventHandler:ig_qa,addDOMEventHandler:ig_ra,addCustomEventHandler:ig_sa,removeEventHandler:ig_ta,removeModuleEventHandler:ig_ua,removeDOMEventHandler:ig_va,removeCustomEventHandler:ig_wa,triggerEvent:ig_xa,triggerModuleEvent:ig_za,triggerCustomEvent:ig_Ba,triggerDelayedEvent:ig_ya,triggerDelayedModuleEvent:ig_Aa,triggerDelayedCustomEvent:ig_Ca},_IG_AddEventHandler=
ig_F.addEventHandler,_IG_AddModuleEventHandler=ig_F.addModuleEventHandler,_IG_AddGadgetEventHandler=ig_F.addModuleEventHandler,_IG_AddDOMEventHandler=ig_F.addDOMEventHandler,_IG_AddCustomEventHandler=ig_F.addCustomEventHandler,_IG_RemoveEventHandler=ig_F.removeEventHandler,_IG_RemoveModuleEventHandler=ig_F.removeModuleEventHandler,_IG_RemoveGadgetEventHandler=ig_F.removeModuleEventHandler,_IG_RemoveDOMEventHandler=ig_F.removeDOMEventHandler,_IG_RemoveCustomEventHandler=ig_F.removeCustomEventHandler,
_IG_TriggerEvent=ig_F.triggerEvent,_IG_TriggerModuleEvent=ig_F.triggerModuleEvent,_IG_TriggerGadgetEvent=ig_F.triggerModuleEvent,_IG_TriggerCustomEvent=ig_F.triggerCustomEvent,_IG_TriggerDelayedEvent=ig_F.triggerDelayedEvent,_IG_TriggerDelayedModuleEvent=ig_F.triggerDelayedModuleEvent,_IG_TriggerDelayedGadgetEvent=ig_F.triggerDelayedModuleEvent,_IG_TriggerDelayedCustomEvent=ig_F.triggerDelayedCustomEvent;_IG_AddDOMEventHandler(window,"unload",ig_F.tb);_IG_AddDOMEventHandler(window,"load",function(){_IG_TriggerEvent("load")});
_IG_AddDOMEventHandler(window,"unload",function(){_IG_TriggerEvent("unload")});_IG_AddDOMEventHandler(window,"resize",function(){_IG_TriggerEvent("resize")});function _IG_RegisterOnloadHandler(a){_IG_AddEventHandler("domload",a)}function _IG_LoadLibraryDeferred(a,b){_IG_RegisterOnloadHandler(function(){_IG_LoadScript(a,b)})}_exportSymbols("google.gadgets.Events",["addHandler",_IG_AddEventHandler,"removeHandler",_IG_RemoveEventHandler,"addOnloadHandler",_IG_RegisterOnloadHandler]);
function _IG_RegisterMaximizeHandler(a,b){_IG_AddModuleEventHandler(a,"unmaximize",function(){b(ig_a)});_IG_AddModuleEventHandler(a,"maximize",function(){b(ig_b)})};var _currentLayout,_layoutData,_IG_Layouts={savedModulePositions:ig_};_IG_Layouts._selectLayout=function(a){var b=_gel("edit_this_tab_form").edit_this_tab_selected_layout;for(var c=0;c<b.length;c++){var d=b[c].value,e=_gel("edit_this_tab_layoutimg_"+d);if(d!=a){b[c].checked=ig_a;if(e.src.indexOf("_highlight")!=-1)e.src=e.src.substring(0,e.src.indexOf("_highlight"))+".gif"}else{b[c].checked=ig_b;if(e.src.indexOf("_highlight")==-1)e.src=e.src.substring(0,e.src.indexOf(".gif"))+"_highlight.gif"}}};
_IG_Layouts._renderLayout=function(a){if(!_IG_Layouts.isLayoutValid(a))return ig_a;var b=_IG_Layouts.getColumnsInOrder(),c=_layoutData[a],d=ig_a;for(var e=0;e<b.length;e++){b[e].style.width=c.sizes[e];if(b[e].style.display!=c.display[e]){b[e].style.display=c.display[e];d=ig_b}}if((a==_currentLayout||d)&&!_IG_Layouts.rearrangeModules(a))return ig_a;return ig_b};
_IG_Layouts.rearrangeModules=function(a){if(!_IG_Layouts.isLayoutValid(a))return ig_a;var b=_IG_Layouts.getColumnsInOrder(),c=_gel("lc_opt"),d=b[_layoutData[a].visibleColumns-1];d.insertBefore(c,d.firstChild);if(_IG_Layouts.savedModulePositions!=ig_&&a==_currentLayout){for(var e=0;e<b.length;e++){var f=_IG_Layouts.savedModulePositions[e];for(var g=0;g<f.length;g++){var h=_gel(f[g]);h!=ig_&&b[e].insertBefore(h,b[e].lastChild)}}return ig_b}var j=[],l=[];for(var e=0;e<b.length;e++)l.push(b[e].firstChild);
var n=ig_a;do{n=ig_a;for(var e=0;e<l.length;e++){while(l[e]!=ig_&&l[e].id.indexOf("m_")==-1)l[e]=l[e].nextSibling;if(l[e]!=ig_&&l[e].id.indexOf("m_")!=-1){j.push(l[e].id);n=ig_b;l[e]=l[e].nextSibling}}}while(n);var o=0;for(var g=0;g<j.length;g++){b[o].insertBefore(_gel(j[g]),b[o].lastChild);do{o++;if(o>=b.length)o=0}while(b[o].style.display=="none")}return ig_b};
_IG_Layouts._saveModulePositions=function(){var a=_IG_Layouts.getColumnsInOrder();_IG_Layouts.savedModulePositions=[];for(var b=0;b<a.length;b++){_IG_Layouts.savedModulePositions[b]=[];var c=_IG_Layouts.savedModulePositions[b];for(var d=0;d<a[b].childNodes.length-1;d++){var e=a[b].childNodes[d];e.tagName=="DIV"&&e.id.indexOf("m_")!=-1&&c.push(e.id)}}};
_IG_Layouts._editTabSettingsSubmit=function(a){var b=_gel("edit_this_tab_form").edit_this_tab_selected_layout,c=-1;for(var d=0;d<b.length;d++)if(b[d].checked==ig_b)c=b[d].value;var e="",f=_gel("edit_this_tab_name").value;if(_gel("tab"+a+"_view_title").innerHTML!=f&&f!=""){e+="rt_"+a+"="+_esc(f);_gel("tab"+a+"_view_title").innerHTML=_hesc(f);_gel("tab"+a+"_title").value=_hesc(f);var g=_gel("tip_tabtitle");if(g!=ig_)g.innerHTML=_hesc(f)}if(c!=_currentLayout){e+=e==""?"":"&";e+="lt_"+a+"="+c;_currentLayout=
c;var h=_IG_Layouts.getColumnsInOrder(),j="";for(var l=0;l<h.length;l++)for(var n=0;n<h[l].childNodes.length-1;n++){var o=h[l].childNodes[n];if(o.tagName=="DIV"&&o.id.indexOf("m_")!=-1){j+=j==""?"":":";j+=o.id.substring(2)+"_"+(l+1)}}e+="&mp="+_esc(j)}e!=""&&_xsetp(e);_IG_Layouts.savedModulePositions=ig_};_IG_Layouts._editTabSettingsCancel=function(){_IG_Layouts._renderLayout(_currentLayout);_IG_Layouts.savedModulePositions=ig_};
_IG_Layouts.getColumnsInOrder=function(){var a=4,b=[];for(var c=1;c<=a;c++){var d=_gel("c_"+c);if(d==ig_)break;b.push(d)}return b};_IG_Layouts.isLayoutValid=function(a){if(a<0||a>_layoutData.length-1)return ig_a;return ig_b};function _IG_Prefs_PrefsData(){}_IG_Prefs_PrefsData.prototype.value=ig_;
function _IG_Prefs(a){var b=a;if(typeof remote_modules!=="object"){var c=_args().mid;b=c?c:0;_IG_Prefs._parseURL(b);_IG_Prefs.Q[b]=ig_a}else{if(!b)throw new Error("Module ID is required as first argument to _IG_Prefs() for inlined modules");_IG_Prefs.Q[b]=ig_b}_IG_Prefs.d[_IG_Prefs.q+b]||(_IG_Prefs.d[_IG_Prefs.q+b]={});this.d=_IG_Prefs.d[_IG_Prefs.q+b];this.b=b;this.Xb=/(.*)(\<ph.*?\>\s*(\<ex\>(.*?)\<\/ex\>)?\s*%1\s*\<\/ph\>)(.*)/}
_IG_Prefs.prototype.B=function(a,b){if(b==undefined)b=ig_;var c=this.d[a];if(c==undefined)return b;var d=c.value;return d!=undefined?d:b};_IG_Prefs.prototype.O=function(a,b){return this.B(_IG_Prefs.h+a,b)};_IG_Prefs.prototype.A=function(a){var b="",c=this.O(a,b);return c!=ig_?c+"":b};_IG_Prefs.prototype.ma=function(a){var b=0,c=parseInt(this.O(a,b),10);return isNaN(c)?b:c};_IG_Prefs.prototype.ka=function(a){var b=this.A(a);return b==="true"||!!parseInt(b,10)};
_IG_Prefs.prototype.ja=function(a){return _IG_Prefs._strToArray(this.O(a,""))};_IG_Prefs.prototype.Fa=function(a,b){this.set(a,_IG_Prefs._arrayToStr(b))};_IG_Prefs.prototype.la=function(){return this.A(".country")};_IG_Prefs.prototype.na=function(){return this.A(".lang")};_IG_Prefs.prototype.oa=function(a){return this.B(_IG_Prefs.Ka+a,"")+""};
_IG_Prefs.prototype.set=function(){var a=Math.floor(arguments.length/2);if(a==0)return;var b=[],c=[];for(var d=0;d<a;++d){var e=arguments[d*2],f=_IG_Prefs.h+e,g=arguments[d*2+1];if(this.hb(f,g)){b.push(f,g);c.push(e,g)}}if(b.length==0)return;_IG_Prefs.Q[this.b]?_IG_Prefs._setP(this.b,c):_IFPC_SetPref(c)};_IG_Prefs.prototype.qa=function(){var a=["__module_id__="+this.b];for(var b in this.d)a.push(encodeURIComponent(b)+"="+encodeURIComponent(this.d[b].value));return a.join("&")};
_IG_Prefs.prototype.dump=function(){document.write("<pre>");for(var a in this.d)document.writeln(a+" = "+this.B(a,ig_));document.write("</pre>")};_IG_Prefs.prototype.hb=function(a,b){var c=this.d[a];if(c&&c.value===b)return ig_a;if(c)c.value=b;else{c=new _IG_Prefs_PrefsData;c.value=b;this.d[a]=c}return ig_b};_IG_Prefs.Q={};_IG_Prefs.d={};_IG_Prefs.q="m_";_IG_Prefs.h="up_";_IG_Prefs.ib="up_";_IG_Prefs.Ka="msg_";_IG_Prefs.X={};_IG_Prefs.X[_IG_Prefs.ib]="value";
_IG_Prefs.Wb=function(a,b){if(a.indexOf)return a.indexOf(b);else{for(var c=0;c<a.length;++c)if(a[c]===b)return c;return-1}};
_IG_Prefs._parseURL=function(a){_IG_Prefs.Q[a]=ig_a;var b={},c=ig_j();for(var d=0;d<c.length;++d){var e=c[d].indexOf("=");if(e>=0){var f=c[d].substring(0,e);f=f.replace(/\+/g," ");var g=c[d].substring(e+1);g=g.replace(/\+/g," ");g=_unesc(g);var h=ig_a;for(var j in _IG_Prefs.X)if(f.indexOf(j)===0){h=ig_b;f=f.substring(j.length);f=_IG_Prefs.h+f;b[f]=b[f]?b[f]:new _IG_Prefs_PrefsData;if(j===_IG_Prefs.Vb||j===_IG_Prefs.Ub)g=g=="true";b[f][_IG_Prefs.X[j]]=g;break}if(!h)if(f.indexOf(_IG_Prefs.Ka)===0)_IG_Prefs._add(a,
f,g);else if(f===".lang"||f===".country")_IG_Prefs._add(a,_IG_Prefs.h+f,g)}}if(window.IDIModule){var b=window.IDIModule.getPrefs();for(var d in b)_IG_Prefs._add(a,d,b[d])}else for(var f in b)_IG_Prefs._add(a,f,b[f].value)};_IG_Prefs._add=function(a,b,c){var d=_IG_Prefs.q+a;if(typeof _IG_Prefs.d[d]!=="object")_IG_Prefs.d[d]={};if(typeof _IG_Prefs.d[d][b]!=="object")_IG_Prefs.d[d][b]=new _IG_Prefs_PrefsData;else return;var e=_IG_Prefs.d[d][b];e.value=c};
_IG_Prefs.Pb=function(a,b,c){var d=_IG_Prefs.q+a;if(typeof _IG_Prefs.d[d]!=="object")_IG_Prefs._add(a,b,c);else if(typeof _IG_Prefs.d[d][b]!=="object")_IG_Prefs.d[d][b]=new _IG_Prefs_PrefsData;var e=_IG_Prefs.d[d][b];e.value=c};_IG_Prefs._addAll=function(a,b){for(var c=0;c<b.length;++c)_IG_Prefs._add(a,b[c][0],b[c][1])};_IG_Prefs._arrayToStr=function(a){var b=a.length&&a.join;if(b){var c=[];for(var d=0;d<a.length;++d)c.push(a[d].replace(/\|/g,"%7C"));return c.join("|")}else return new String(a)};
_IG_Prefs._strToArray=function(a){var b=a.length>0?a.split("|"):[];for(var c=0;c<b.length;++c)b[c]=b[c].replace(/%7C/g,"|");return b};
_IG_Prefs._updatePrefsInUrl=function(a,b){var c=_IG_Prefs.q+a,d=_IG_Prefs.d[c];if(d==ig_)return b;var e=b.split("&");for(var f=0;f<e.length;++f)e[f].indexOf(_IG_Prefs.h)===0&&e.splice(f--,1);for(var g in d){if(g.indexOf(_IG_Prefs.h)!==0||g.indexOf(_IG_Prefs.h+".lang")===0||g.indexOf(_IG_Prefs.h+".country")===0||g.indexOf(_IG_Prefs.h+"synd")===0)continue;e.push(_esc(g)+"="+_esc(d[g].value))}return e.join("&")};
_IG_Prefs._setPrefs=function(a,b){var c=Math.floor(b.length/2);for(var d=0;d<c;++d){var e=_IG_Prefs.h+b[d*2],f=b[d*2+1];_IG_Prefs.Pb(a,e,f)}};_IG_Prefs._setP=function(a,b){if(_args().synd==="open")return;var c=Math.floor(b.length/2),d=[];for(var e=0;e<c;++e){var f=_IG_Prefs.h+b[e*2],g=b[e*2+1];d.push(_IG_Prefs.q+a+"_"+f+"="+_esc(g))}if(d.length===0)return;_xsetp(d.join("&"))};
_exportClass("google.gadgets","Prefs",_IG_Prefs,["getString",_IG_Prefs.prototype.A,"getInt",_IG_Prefs.prototype.ma,"getBool",_IG_Prefs.prototype.ka,"getArray",_IG_Prefs.prototype.ja,"setArray",_IG_Prefs.prototype.Fa,"getLang",_IG_Prefs.prototype.na,"getCountry",_IG_Prefs.prototype.la,"getMsg",_IG_Prefs.prototype.oa,"getPreloadedString",_IG_Prefs.prototype.qa,"set",_IG_Prefs.prototype.set,"dump",_IG_Prefs.prototype.dump]);function _IG_FR_toggle(a,b,c,d){c=c||"";d=d||"";var e=_gel("ft_"+a+"_"+b),f=_gel("fb_"+a+"_"+b),g=_gel("ftl_"+a+"_"+b);if(f.style.display=="block")ig_G(e,f,g,c);else{var h=eval("FEED"+a);if(!h.has_entries&&!h.is_fetching){h.is_fetching=ig_b;_IG_FetchFeedAsJSON(h.url,_IG_Callback(ig_Da,a,b,c,d),h.num_items+15,ig_b)}else{for(var j=0;j<eval("FEED"+a).num_items;j++){var l=_gel("ftl_"+a+"_"+j);l&&ig_G(_gel("ft_"+a+"_"+j),_gel("fb_"+a+"_"+j),l,c)}ig_Ea(e,f,g,d);if(f.style.maxHeight&&parseInt(f.style.maxHeight,
10)<ig_Fa(g.offsetWidth,f))f.style.height=f.style.maxHeight}}}function ig_Da(a,b,c,d,e){var f=eval("FEED"+b);f.is_fetching=ig_a;if(a&&a.Entry){for(var g=0;g<a.Entry.length;g++)if(a.Entry[g].ID!="no_id"){var h=_gel("fb_"+b+"_"+a.Entry[g].ID);if(h)h.innerHTML=a.Entry[g].Summary}eval("FEED"+b).has_entries=ig_b;_IG_FR_toggle(b,c,d,e)}}function ig_H(a){return a.className.match("reverse_directionality$")=="reverse_directionality"}
function ig_G(a,b,c,d){a.className=ig_H(a)?"fmaxbox_reverse_directionality":"fmaxbox";a.title=d;if(_old_html||_use_old_feed_styles)a.className="fbox fmaxbox";b.style.display="none";b.style.maxHeight="";c.className=ig_H(a)?"uftl_reverse_directionality":"uftl"}
function ig_Ea(a,b,c,d){a.className=ig_H(a)?"fminbox_reverse_directionality":"fminbox";a.title=d;if(_old_html||_use_old_feed_styles)a.className="fbox fminbox";b.style.display="block";b.style.maxHeight=b.offsetWidth*1.5+"px";c.className=ig_H(a)?"sftl_reverse_directionality":"sftl"}
function ig_Fa(a,b){var c=document.createElement("div");c.style.left=-screen.width;c.style.top=-screen.height;c.style.width=a;c.innerHTML=b.innerHTML;document.body.appendChild(c);var d=c.clientHeight;document.body.removeChild(c);return d}function _IG_RegisterContainerScrollHandler(a){if(navigator.userAgent.indexOf("Firefox")>=0)window.addEventListener("scroll",a,ig_a);else window.onscroll=a}function _IG_GetContainerVisibleHeight(){return document.documentElement.clientHeight}
function _IG_GetContainerTotalHeight(){return document.body.scrollHeight}function _IG_GetContainerScrollTop(){return document.documentElement.scrollTop}function ig_I(a){var b=_gel("hl"),c=b?b.value:"en";return"/reader/ig/feed/"+_esc(eval("FEED"+a).url)+"?hl="+c}function ig_J(a,b){if(window._max_strategies){var c=ig_I(a)+(b?"&i="+b:"");window._max_strategies[a]._updateIframeSrc(c)}}function _IG_FR_maxModule(a,b,c){ig_J(a,b);window._IG_maximize_view(a,"feed",c)}
function _IG_FR_init(a){window._max_strategies[a]=new window._IG_inlinedTransitionStrategy(a,ig_I(a),ig_,_IG_isIE());_IG_AddModuleEventHandler(a,"unmaximize",function(){ig_J(a)})};window._IG_PU=(function(){var a=ig_b,b;function c(d){if(!arguments.callee.calledOnce){var e={IG_PU_box:"div",IG_PU_iframe_cover:"iframe",IG_PU_bg:"div"};for(var f in e){var g=document.createElement(e[f]);g.id=f;g.style.display="none";document.body.insertBefore(g,document.body.firstChild)}arguments.callee.calledOnce=ig_b}return _gel(d)}return{open:function(d,e,f,g){a=typeof e=="string";var h=c("IG_PU_box");if(h&&h.style.display=="none"){f||(f=[_IG_PU_MakeDialogButton("Save"),_IG_PU_MakeDialogButton("Cancel")]);
var j=["<table class=dialog id=IG_PU_dlg cellspacing=0 cellpadding=0>","<tr><td>",'<div class=outerborder><div class="border titlebar">',d,"</div>",'<div class="border body" id=dialogcontent>',a?e:"",ig_K(f),"</div>","</td></tr></table>"].join("");ig_Ga(j,g,a?ig_:e)}},openUrl:function(d,e,f,g,h,j){var l=ig_Ha(d)+(e||""),n=["<div class=url>",'<iframe id=popup_iframe style="width:',g,';height:0px;"',' src="',f,'" onload="_ResizeIframeHeight();"'," scrolling=no frameborder=0></iframe>","<div class=c></div>",
ig_K(h,"colored_background")].join("");window._IG_PU.open(l,n,[],j)},hide:function(d){var e=_gel("button_"+d);if(e&&e.firstChild&&e.firstChild.disabled)return;c("IG_PU_box").style.display="none";c("IG_PU_iframe_cover").style.display="none";var f=c("IG_PU_bg");f.onclick="";f.style.height="";f.style.width="";if(!a){var g=_gel("dialogcontent").firstChild;d!=_DI_button_type.OK&&g.nodeName=="FORM"&&g.reset();setTimeout(function(){var h=_gel("popup_box_placeholder"),j=_gel("dialogcontent").firstChild;h.parentNode.insertBefore(j,
h);h.parentNode.removeChild(h)},1000)}_IG_RemoveEventHandler("resize",_gel("popup_iframe")?_ResizeIframeHeight:ig_L);window.onscroll=ig_;b(d)},createSimpleTitle:function(d){return["<div class=popup_title>",d,"</div>","<div class=popup_title_buttons>",'<a onclick="_IG_PU_hide(_DI_button_type.Close);"',' class=delbox  href="javascript:void(0)">',"</a>","</div>","<div class=c></div>"].join("")},findFocusable:function(d,e,f){if(!d.disabled){var g=d.nodeName.toLowerCase();if(g=="input")return d;if(g==
"button")return d;if(!f){if(g=="a"&&ig_M(d,"href"))return d;if(d.nodeType==1&&ig_M(d,"tabindex")&&d.tabIndex!=-1)return d}}if(!d.hasChildNodes())return ig_;var h=d.childNodes;for(var j=e?0:h.length-1,l;l=h[j];e?j++:j--){var n=ig_N(l,e,f);if(n)return n}return ig_},makeDialogButton:function(d,e,f,g){var h=["<input type=button"];e&&h.push(' id="'+e+'"');f&&h.push(' class="'+f+'"');g&&h.push(' onclick="'+g+'"');h.push(' value="',d,'"></input>');return h.join("")},disableHideForButton:function(d){var e=
_gel("button_"+d);if(e)e.onclick=function(){}},createSimpleInputBox:function(d,e,f){return['<div class="popup_body thinpadding">','<form onsubmit="_IG_PU_hide(_DI_button_type.OK); return false;">',"<table cellspacing=0 cellpadding=0 border=0><tr>","<td class=sidepadding>",_hesc(e),"</td>","<td class=sidepadding>",'<input id="',_hesc(d),'" name="',_hesc(d),'" ','type=text size=45 value="'+_hesc(f)+'">',"</td>","</tr></table></form></div>"].join("")},hasAttr:function(d,e){if(d.getAttributeNode){var f=
d.getAttributeNode(e);return f?f.specified:ig_a}return d.getAttribute(e)!=ig_},limitFocus:function(d){if(!d)d=window.event;var e=d.target?d.target:d.srcElement,f=d.keyCode||d.charCode||d.which;if(f==9){var g=ig_N(this,ig_b,ig_a);if(!g)return ig_b;var h=ig_N(this,ig_a,ig_a);if(e==g&&d.shiftKey&&!(d.ctrlKey||d.altKey)){h.focus();return ig_a}else if(e==h&&!(d.shiftKey||d.ctrlKey||d.altKey)){g.focus();return ig_a}}return ig_b},buildButtons:function(d,e){if(!d||!d.length)return"";var f=['<div id=buttons class="button_background'];
e&&f.push(" "+e);f.push('"><table class=buttontable cellspacing=0 cols=');f.push(d.length,"><tr>");for(var g=0;g<d.length;++g){f.push("<td align=center>");f.push('<span id="button_',g,'" ');f.push('onclick="_IG_PU_hide(',g,')">');f.push(d[g]);f.push("</span>");f.push("</td>")}f.push("</tr></table></div></div>");return f.join("")},showDialog:function(d,e,f){if(e){if(typeof e!="function")e=function(){};b=e}else b=function(){};var g=c("IG_PU_bg"),h=g.style;h.zIndex=3000;h.background="#000";ig_Ia(g,ig_b);
h.position="absolute";g.onclick=function(){};h.display="none";h.left="0px";h.top="0px";var j=c("IG_PU_box"),l=c("IG_PU_iframe_cover");j.innerHTML=d;if(!a&&f){var n=document.createElement("div");n.id="popup_box_placeholder";n.style.display="none";f.parentNode.insertBefore(n,f);_gel("dialogcontent").insertBefore(f,_gel("dialogcontent").firstChild)}var o=j.style;o.position="absolute";o.zIndex=3001;var p=l.style;p.position="absolute";o.visibility="hidden";o.display="block";ig_L();o.visibility="visible";
p.display="";h.display="block";_IG_AddEventHandler("resize",_gel("popup_iframe")?_ResizeIframeHeight:ig_L);window.onscroll=ig_L;_gel("IG_PU_dlg").onkeydown=ig_Ja;var r=ig_N(j,ig_b,ig_b);r&&r.focus()},position:function(){var d=c("IG_PU_box"),e=c("IG_PU_iframe_cover"),f=c("IG_PU_bg"),g=document.body.clientWidth,h=window.innerHeight;if(!h)h=document.documentElement.offsetHeight;var j=d.offsetHeight<h,l=d.style;if(d){var n=(g-d.offsetWidth)/2,o=Math.max((h-d.offsetHeight)/2+(self.pageYOffset?self.pageYOffset:
document.documentElement&&document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop),0);if(!j&&l.top)o=parseInt(l.top,10);l.left=n+"px";l.top=o+"px";var p=e.style;p.left=n+"px";p.top=o+"px";p.width=d.offsetWidth+"px";p.height=d.offsetHeight+"px"}if(f){var r=parseInt(l.top,10)+d.offsetHeight,s=Math.max(ig_E(),h,r);f.style.height=s+"px";f.style.width=document.body.clientWidth+"px"}},toggleTransparency:function(d,e){var f=d.style;if("opacity"in f)f.opacity=e?0.5:1;
else if("MozOpacity"in f)f.MozOpacity=e?0.5:1;else if("filter"in f)f.filter=e?"alpha(opacity=50)":"alpha(opacity=100)"},resizeIframeHeight:function(){var d=_gel("popup_iframe");if(d){var e=d.style;e.height=ig_E(d.contentWindow.document.body)+"px";e.display="block";e.display=""}ig_L()}}})();
var _DI_button_type={Close:-1,OK:0,Cancel:1},_IG_PU_hide=window._IG_PU.hide,_IG_PU_open=window._IG_PU.open,_IG_PU_openURL=window._IG_PU.openUrl,_IG_PU_disable_hide_for_button=window._IG_PU.disableHideForButton,_IG_PU_MakeDialogButton=window._IG_PU.makeDialogButton,_ResizeIframeHeight=window._IG_PU.resizeIframeHeight,ig_Ia=window._IG_PU.toggleTransparency,ig_Ha=window._IG_PU.createSimpleTitle,ig_N=window._IG_PU.findFocusable,ig_M=window._IG_PU.hasAttr,ig_Ja=window._IG_PU.limitFocus,ig_K=window._IG_PU.buildButtons,
ig_L=window._IG_PU.position,ig_Ga=window._IG_PU.showDialog;function _IG_PU_init(){}function _IG_PU_IGNORE(){};var ig_O,ig_P,ig_Q={};function _IG_AddDropDownEventHandler(a,b){ig_Q[a]=b}function _IG_DD_init(){document.write('<iframe id="IG_DD_iframe_cover" class="dd_iframe_cover" style="display:none;"></iframe>');document.write('<div id="IG_DD_div" class="dd_layer_hidden" onclick="_IG_DD_hide();return true;"></div>')}
function _IG_DD_create(a,b){var c=document.createElement("div");c.setAttribute("id","DD_"+a);c.className="dd dd_border";c.style.display="none";c.onkeydown=_IG_DD_keys;for(var d=0,e;e=b[d];d++){e[3]&&c.appendChild(ig_Ka(e[3]));c.appendChild(_IG_DD_add(e[0],e[1],e[2],d))}_gel("IG_DD_div").appendChild(c)}
function _IG_DD_add(a,b,c,d){b=b||"javascript:void(0)";var e=document.createElement("div"),f="";if(typeof c=="string"&&c!="")f=' onclick="'+c+'"';e.innerHTML='<a href="'+b+'"'+f+">"+a+"</a>";var g=e.firstChild;if(typeof c=="string"&&c!="")c=g.onclick;if(c)g.onclick=function(h){c(h);_IG_DD_hide();return ig_a};g.className=d==0?"dd_item dd_item_first":"dd_item";g.onblur=function(){ig_P=ig_a;return ig_b};g.onmouseover=function(){return _IG_DD_select(this)};return g}
function ig_Ka(a){var b=document.createElement("div");b.className=a;b.innerHTML='<div class="topline"></div><div class="bottomline"></div>';return b}
function _IG_DD_open(a,b){var c=_gel("DD_"+b);if(c.style.display=="none"){ig_O=b;var d=_gel("IG_DD_div");d.className="dd_layer";_IG_AddEventHandler("resize",_IG_DD_position);_IG_DD_position();ig_P=ig_a;if(c.hasChildNodes()){var e=c.firstChild;if(e.tagName!="A")e=e.nextSibling;_IG_DD_select(e)}var f=_gel("DD_tg_"+b);f.className+=" ddbox_sel";var g=ig_Q[ig_O];g&&g(ig_b)}}
function _IG_DD_position(){var a=_gel("DD_"+ig_O),b=_gel("DD_tg_"+ig_O),c=_gel("IG_DD_div");a.style.display="block";var d=_findPos(b),e=a.offsetWidth,f=d[0]+b.offsetWidth-e,g=document.body.clientWidth+document.body.scrollLeft;if(f<5)f=5;else if(f+e>g-5)f=g-5-e;a.style.left=f+"px";a.style.top=d[1]+b.offsetHeight+"px";var h=_gel("IG_DD_iframe_cover");h.style.left=a.style.left;h.style.top=a.style.top;h.style.width=a.offsetWidth+"px";h.style.height=a.offsetHeight+"px";h.style.display="block";c.style.height=
ig_E()+"px";c.style.width=document.body.clientWidth+"px"}
function _IG_DD_hide(){var a=_gel("IG_DD_div");if(a.className=="dd_layer"){_IG_RemoveEventHandler("resize",_IG_DD_position);if(ig_O){var b=_gel("DD_"+ig_O);b.style.display="none";_gel("IG_DD_iframe_cover").style.display="none";var c=_gel("DD_tg_"+ig_O);c.className=c.className.replace(/ ddbox_sel/,"");var d=ig_Q[ig_O];d&&d(ig_a);if(ig_P){var e=_gel("DD_tg_"+ig_O);e&&e.focus()}ig_P=ig_a;ig_O=ig_}a.className="dd_layer_hidden"}_IG_DD_select(ig_)}
function _IG_DD_gcn(a,b,c){var d=new RegExp("(^| )"+c+"( |$)"),e=a.getElementsByTagName(b),f=[];for(var g=0,h;h=e[g];g++)d.test(h.className)&&f.push(h);return f}
function _IG_DD_select(a){var b=_IG_DD_gcn(_gel("IG_DD_div"),"a","dd_sel");if(b!=ig_)for(var c=0,d;d=b[c];c++)d.className=d.className.replace(/ dd_sel/g,"");if(a){try{a.focus()}catch(e){if(!(e.message=="Can't move focus to the control because it is invisible, not enabled, or of a type that does not accept the focus."))throw e;}a.className=a.className+" dd_sel"}}
function _IG_DD_keys(a){function b(g,h){var j=g;do{j=h?j.nextSibling:j.previousSibling;if(!j){var l=g.parentNode;j=h?l.firstChild:l.lastChild}}while(j!=g&&j.tagName!="A");return j}var c=ig_b,d=_IG_DD_gcn(_gel("IG_DD_div"),"a","dd_sel");if(d==ig_||d.length!=1)return ig_b;var e=d[0];if(!a)a=window.event;var f=a.keyCode||a.charCode||a.which;switch(f){case 13:ig_P=ig_b;break;case 38:_IG_DD_select(b(e,ig_a));c=ig_a;break;case 40:_IG_DD_select(b(e,ig_b));c=ig_a;break;case 27:case 9:ig_P=ig_b;c=ig_O==ig_&&
f==9;_IG_DD_hide();break}return c};function ig_La(a,b,c,d){a||c(d?ig_:"");var e=eval("("+a.substring(27)+")");if(b in e){var f=e[b].body;c(d?ig_R(f):f)}}function ig_Ma(a){var b;if(window.ActiveXObject){b=new ActiveXObject("Microsoft.XMLDOM");b.async=ig_a;b.validateOnParse=ig_a;b.resolveExternals=ig_a;b.loadXML(a)}else{var c=new DOMParser;b=c.parseFromString(a,"text/xml")}return b}
function ig_R(a){var b=ig_Ma(a),c=b.documentElement;if(c&&c.nodeName=="parsererror"||navigator.userAgent.indexOf("Safari")>=0&&b.getElementsByTagName("parsererror")[0])return a;return b}var ig_Na=(new Date).getTime();
function ig_S(a){if(!a.post_data&&!a.headers&&window._pl_data&&_pl_data[a.url]&&!(!isNaN(a.refreshInterval)&&a.refreshInterval>=0&&(new Date).getTime()>ig_Na+a.refreshInterval*1000)){if(a.asXml){var b=ig_R(_pl_data[a.url]);a.callback(b)}else a.callback(_pl_data[a.url]);return}var c="/ig/jsonp?";if(_et!="")c+="et="+_et+"&";if(!isNaN(a.refreshInterval)&&a.refreshInterval>=0)c=_appendMaxAgeParameter(c,a.refreshInterval);if(a.encoding)c+="enc="+_esc(a.encoding)+"&";if(a.headers){var d=[];for(var e=0;e<
a.headers.length;e++)d.push(_esc(a.headers[e][0]+":"+a.headers[e][1]));c+="hdrs="+_esc(d.join(","))+"&"}c+="url="+_esc(a.url);_sendx(c,function(f){ig_La(f,a.url,a.callback,a.asXml)},ig_a,a.post_data)}function ig_T(a){var b={};for(var c in a)b[c]=a[c];return b}function _IG_FetchContent(a,b,c){var d;d=c!=ig_&&typeof c=="object"?ig_T(c):{};d.url=a;d.callback=b;d.asXml=ig_a;ig_S(d)}
function _IG_FetchXmlContent(a,b,c){var d;d=c!=ig_&&typeof c=="object"?ig_T(c):{};d.url=a;d.callback=b;d.asXml=ig_b;ig_S(d)}function ig_Oa(a,b,c){_IG_FetchContent(a,function(d){if(d){var e=ig_R(d);if(typeof e=="object"&&e.firstChild){var f=e.firstChild;f.nodeType==7&&f.nodeName=="xml"&&e.removeChild(f);b(e);return}}b(ig_)},c)}
function ig_U(a,b){var c="/ig/feedjson";_sendx(c,function(d){var e={};try{e=eval("("+d.slice(27)+")")}catch(f){e={}}for(var g in b){var h=e[g]?e[g]:ig_;b[g](h)}b=ig_},ig_a,a)}var ig_V=ig_a,ig_Pa=0,ig_W="",ig_X={};
function _IG_FetchFeedAsJSON(a,b,c,d,e){if(typeof e!="object")e={};var f="fr_"+ig_Pa++,g="url="+_esc(a);if(!isNaN(e.refreshInterval)&&e.refreshInterval>=0)g=_appendMaxAgeParameter(g,e.refreshInterval);if(c)g+="&val="+_esc(c);if(d)g+="&sum=1";var h=f+"="+_esc(g);if(ig_V){var j={};j[f]=b;ig_U(h,j)}else{if(ig_W!="")ig_W+="&";ig_W+=h;ig_X[f]=b}}function ig_Qa(){ig_V=ig_b;ig_W!=""&&ig_U(ig_W,ig_X);ig_W="";ig_X=ig_}_IG_AddEventHandler("domload",ig_Qa);
_exportSymbols("google.gadgets.Fetchers",["getContent",_IG_FetchContent,"getXMLContent",ig_Oa,"getFeedAsJSON",_IG_FetchFeedAsJSON]);function _hide_sent_content_messages(){_gel("sent_content_msg").className="hidden_msg";_gel("sent_tab_box").className="hidden_msg_box";_gel("send_tab_error_box").className="hidden_msg_box";_gel("sent_gadget_box").className="hidden_msg_box"}var ig_Y=ig_;
function _share_gadget(a,b,c,d,e,f,g,h){if(d){_hide_sent_content_messages();if(!ig_Y)ig_Y=_gel("sent_gadget_box").innerHTML;_gel("sent_gadget_box").innerHTML=ig_Y.replace("GADGET_NAME",_get_module_title(d))}var j=g?"_gel('popup_iframe').contentWindow.prepareEmail(_gel('share_userprefs') ? _gel('share_userprefs').checked : false)":"_gel('popup_iframe').contentWindow.prepareEmail();",l=['<input type="button" id="send_btn" disabled="true" onclick="'+j+'" value="'+e+'"></input>',_IG_PU_MakeDialogButton(f)],
n="titlebar userprefs userprefs_border",o=_get_userprefs_checkbox_html(g,h,n);_IG_PU_openURL(a,o,b,c,l,d?_finish_sharing_gadget:ig_);_IG_PU_disable_hide_for_button(0)}
function _share_this_gadget(a,b,c){if(c){_hide_sent_content_messages();if(!ig_Y)ig_Y=_gel("sent_gadget_box").innerHTML;_gel("sent_gadget_box").innerHTML=ig_Y.replace("GADGET_NAME",_get_module_title(c))}_IG_PU_openURL('<img src="/ig/images/sharegadget.gif"> '+a,ig_,b,"555px",ig_,c?_finish_sharing_gadget:ig_);_IG_PU_disable_hide_for_button(0)}
function _share_tab_with_gadget_checkboxes(a,b,c,d,e,f,g){var h='<iframe id="popup_iframe" width="100%" height="0px" src="'+_hesc(b)+'" onload="_ResizeIframeHeight();" scrolling="no"></iframe>',j="_gel('popup_iframe').contentWindow.storeTabAndPrepareEmail(_find_unshared_gadgets(), _gel('share_userprefs') ? _gel('share_userprefs').checked : false);",l=['<input type="button" id="send_btn" disabled="true" onclick="'+_hesc(j)+'" value="'+_hesc(f)+'"></input>',_IG_PU_MakeDialogButton(g)];if(!_uli){_IG_PU_open(a,
h,l);_gel("buttons").className+=" colored_background";return}var n=_get_all_modules(),o=Math.max(n.length*160,400),p=7,r=0;for(var s=0;s<n.length;s++)if(n[s].length>r)r=n[s].length;var k=r>p&&c!="NO_TRANSLATION",i=[a];i.push('<form id="module_list">');i.push('<table class="titlebar module_list_table" ','cols="',n.length,'"',' width="',o,'px">');k?i.push('<tr class="zipped_modules" id="module_list_zipper">'):i.push('<tr class="unzipped_modules">');for(var m=0;m<n.length;m++){i.push('<td width="',100/
n.length,'%" ','valign="top">');for(var q=0;q<n[m].length;q++){var t=_hesc(n[m][q].id.replace("m_","")),u=_hesc(_get_module_title(n[m][q]));i.push('<div class="module_item');q>=p&&k&&i.push(" extra_items");i.push('">');i.push('<input id="share_',t,'" type="checkbox"'," checked ></input>");i.push('<label for="share_',t,'">',u,"</label>");i.push("</div>")}i.push("</td>")}i.push("</tr>");if(k){i.push('<tr class="zipped_module_list">');i.push('<td id="show_all_modules" colspan="',n.length,'" style="font-size:80%;text-align:center;">');
i.push('<a href="javascript:void(0);" id="zipper_text"',' onclick="_modules_zipper();">');i.push(c,"</a>");i.push("</td></tr>")}i.push("</table>");i.push(_get_userprefs_checkbox_html(d,e,"userprefs"));i.push("</form>");_IG_PU_open(i.join(""),h,l);_IG_PU_disable_hide_for_button(0);_gel("dialogcontent").className+=" url";_gel("buttons").className+=" colored_background"}
function _show_shared_userprefs_alert(){if(_gel("share_userprefs").checked){_gel("share_userprefs_alert").style.display="block";_gel("popup_iframe").contentWindow.shouldShareUserprefs(ig_b)}else{_gel("share_userprefs_alert").style.display="none";_gel("popup_iframe").contentWindow.shouldShareUserprefs(ig_a)}}
function _get_userprefs_checkbox_html(a,b,c){var d=[];if(a&&a!=""){d.push('<div class="',c,'">');d.push('<input id="share_userprefs" type="checkbox"');b!=""&&d.push(' onclick="_show_shared_userprefs_alert();"');d.push("></input>");d.push('<label for="share_userprefs">',a,"</label>");b!=""&&d.push('<div class="userprefs_alert"',' id="share_userprefs_alert">',b,"</div>");d.push("</div>")}return d.join("")}
function _modules_zipper(){if(_gel("module_list_zipper").className=="zipped_modules"){_gel("module_list_zipper").className="unzipped_modules";_gel("show_all_modules").style.display="none"}_ResizeIframeHeight()}function _find_unshared_gadgets(){var a=_gel("module_list").elements,b=[];for(var c=0;c<a.length;c++)ig_Ra(a[c])||(b[b.length]=a[c].id.replace("share_",""));return b}
function ig_Ra(a){if(a&&a.tagName=="INPUT"){var b=_gel("module_list_zipper"),c=b&&/unzipped_modules/.test(_gel("module_list_zipper").className),d=/extra_items/.test(a.parentNode.className),e=!b||c||!d;return a.checked&&e}return ig_a}function _finish_sharing_gadget(a){if(a==_DI_button_type.OK){_gel("sent_content_msg").className="msg";_gel("sent_tab_box").className="hidden_msg_box";_gel("send_tab_error_box").className="hidden_msg_box";_gel("sent_gadget_box").className="msg_box"}}
function _finish_sharing_tab(a){_gel("sent_content_msg").className="msg";_gel("sent_gadget_box").className="hidden_msg_box";if(a){_gel("sent_tab_box").className="msg_box";_gel("send_tab_error_box").className="hidden_msg_box"}else{_gel("send_tab_error_box").className="msg_box";_gel("sent_tab_box").className="hidden_msg_box"}};var ig_Z;
ig_Z||(ig_Z=(function(){function a(l){return l<10?"0"+l:l}Date.prototype.o=function(){return this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z"};String.prototype.o=Number.prototype.o=Boolean.prototype.o=function(){return this.valueOf()};var b=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,c=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,d,
e,f={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},g;function h(l){c.lastIndex=0;return c.test(l)?'"'+l.replace(c,function(n){var o=f[n];if(typeof o==="string")return o;return"\\u"+("0000"+(+n.charCodeAt(0)).toString(16)).slice(-4)})+'"':'"'+l+'"'}function j(l,n){var o,p,r,s,k=d,i,m=n[l];if(m&&typeof m==="object"&&typeof m.o==="function")m=m.o(l);if(typeof g==="function")m=g.call(n,l,m);switch(typeof m){case "string":return h(m);case "number":return isFinite(m)?
String(m):"null";case "boolean":case "null":return String(m);case "object":if(!m)return"null";d+=e;i=[];if(typeof m.length==="number"&&!m.propertyIsEnumerable("length")){s=m.length;for(o=0;o<s;o+=1)i[o]=j(o,m)||"null";r=i.length===0?"[]":d?"[\n"+d+i.join(",\n"+d)+"\n"+k+"]":"["+i.join(",")+"]";d=k;return r}if(g&&typeof g==="object"){s=g.length;for(o=0;o<s;o+=1){p=g[o];if(typeof p==="string"){r=j(p,m);if(r)i.push(h(p)+(d?": ":":")+r)}}}else for(p in m)if(Object.hasOwnProperty.call(m,p)){r=j(p,m);if(r)i.push(h(p)+
(d?": ":":")+r)}r=i.length===0?"{}":d?"{\n"+d+i.join(",\n"+d)+"\n"+k+"}":"{"+i.join(",")+"}";d=k;return r}}return{stringify:function(l,n,o){var p=n,r=o,s;d="";e="";if(typeof r==="number")for(s=0;s<r;s+=1)e+=" ";else if(typeof r==="string")e=r;g=p;if(p&&typeof p!=="function"&&(typeof p!=="object"||typeof p.length!=="number"))throw new Error("JSON.stringify");return j("",{"":l})},parse:function(l,n){var o=n,p;function r(s,k){var i,m,q=s[k];if(q&&typeof q==="object")for(i in q)if(Object.hasOwnProperty.call(q,
i)){m=r(q,i);if(m!==undefined)q[i]=m;else delete q[i]}return o.call(s,k,q)}b.lastIndex=0;if(b.test(l))l=l.replace(b,function(s){return"\\u"+("0000"+(+s.charCodeAt(0)).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(l.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){p=eval("("+l+")");return typeof o==="function"?r({"":p},""):p}throw new Error("JSON.parse");}}})());
ig_Z.parse=(function(){var a=ig_Z.parse;return function(b,c){try{return a(b,c)}catch(d){return ig_a}}})();function ig_Sa(a){var b=document.createElement("DIV");b.innerHTML="<iframe onload='this.pool_locked=false'></iframe>";var c=b.getElementsByTagName("IFRAME")[0];c.style.visibility="hidden";c.style.width=c.style.height="0px";c.style.border="0px";c.style.position="absolute";c.pool_locked=a;this.f[this.f.length]=c;b.removeChild(c);return c}
function ig_Ta(a){if(!a.match(/^http[s]?:\/\//))return;var b=this;window.setTimeout(function(){var c=ig_;for(var d=b.f.length-1;d>=0;d--){var e=b.f[d];if(e&&!e.pool_locked){e.parentNode.removeChild(e);if(window.ActiveXObject){b.f[d]=ig_;b.f.splice(d,1)}else{e.pool_locked=ig_b;c=e;break}}}c=c?c:b.sb(ig_b);c.src=a;document.body.appendChild(c)},0)}function ig_Ua(){for(var a=0;a<this.f.length;a++){this.f[a].onload=ig_;this.f[a]=ig_}this.f.length=0;this.f=[]}
function ig_Va(){for(var a=0;a<this.f.length;a++){var b=this.f[a];b&&b.parentNode.removeChild(b)}}function ig_Wa(){this.f=[];this.sb=ig_Sa;this.iframe=ig_Ta;this.clear=ig_Ua;this.dispose=ig_Va}function ig_Xa(a,b){_IFPC.K[a]=b}function ig_Ya(a){delete _IFPC.K[a]}
function ig_Za(a,b,c,d,e,f,g){if(_IFPC.fa)return;c=c.slice(0);c.unshift(_IFPC.Lb(e));c.unshift(f);c.unshift(b);c.unshift(a);var h=4095-d.length;h=parseInt(h/3,10);if(typeof g=="undefined")g=ig_b;var j=_IFPC.Wa(c),l=parseInt(j.length/h,10);if(j.length%h>0)l+=1;for(var n=0;n<l;n++){var o=j.substr(n*h,h),p=[a,_IFPC.Qa,l,n,o,g];_IFPC.sa.iframe(d+"#"+_IFPC.Wa(p))}_IFPC.Qa++}function ig__a(){_IFPC.K={};_IFPC.u={};_IFPC.sa.clear()}
function ig_0a(){if(!_IFPC.fa){_IFPC.fa=ig_b;_IFPC.sa.dispose();_IFPC.clear()}}function ig__(a){var b=_IFPC.da(a)[0],c=ig_;try{c=window.parent.frames[b]}catch(d){}try{if(!c&&window.parent.parent.frames[b]!=window.parent){window.parent.parent.frames[b].setTimeout(function(){},0);c=window.parent.parent.frames[b]}}catch(d){}if(!c)c=window.parent.parent;if(!c||c._IFPC==undefined){c=ig_;return}var e=function(){c._IFPC.handleRequest(a)};window.ActiveXObject?e():c.setTimeout(e,0)}
function ig_1a(a){var a=_IFPC.da(a),b=a.shift(),c=a.shift(),d=a.shift(),e=a.shift(),f=a.shift(),g=a.shift(),h=b+"_"+c;_IFPC.s[h]||(_IFPC.s[h]=[]);_IFPC.s[h].push([e,f]);if(_IFPC.s[h].length==d){_IFPC.s[h].sort(function(k,i){return parseInt(k[0],10)-parseInt(i[0],10)});f="";for(var j=0;j<d;j++)f+=_IFPC.s[h][j][1];_IFPC.s[h]=ig_;var l=_IFPC.da(f),b=l.shift(),n=l.shift(),o=l.shift(),p=l.shift(),r=_IFPC.Db(n);if(r){var s=r.apply(ig_,l);if(_IFPC.Gb(p)){s.unshift(p);_IFPC.call(b,_IFPC.Ja,s,o,ig_,"")}}else if(g)throw new Error("Service "+
n+" not registered.");}}function ig_2a(a){return _IFPC.K.hasOwnProperty(a)?_IFPC.K[a]:ig_}function ig_3a(a){var b="";if(a&&typeof a=="function"){b=_IFPC.Cb();_IFPC.u[b]=a}return b}function ig_4a(a){if(_IFPC.u.hasOwnProperty(a))_IFPC.u[a]=ig_}function ig_5a(a){if(a&&_IFPC.u.hasOwnProperty(a))return _IFPC.u[a];return ig_}function ig_6a(){return _IFPC.Ia+_IFPC.pb++}function ig_7a(a){return(a+"").indexOf(_IFPC.Ia)==0}
function ig_8a(a){var b=a.split("&");for(var c=0;c<b.length;c++){var d=decodeURIComponent(b[c]);try{d=ig_Z.parse(d)}catch(e){}b[c]=d}return b}function ig_9a(a){var b=[];for(var c=0;c<a.length;c++){var d=ig_Z.stringify(a[c]);b.push(encodeURIComponent(d))}return b.join("&")}function ig_$a(a){var b=_IFPC.Ab(a);if(b){var c=[];for(var d=1;d<arguments.length;d++)c[c.length]=arguments[d];b.apply(ig_,c);_IFPC.Sb(a)}else throw new Error("Invalid callbackId");}
var _IFPC={registerService:ig_Xa,unregisterService:ig_Ya,call:ig_Za,clear:ig__a,dispose:ig_0a,relayRequest:ig__,processRequest:ig__,handleRequest:ig_1a,Ia:"cbid",Ja:"ifpc_callback",sa:new ig_Wa,s:{},K:{},u:{},pb:0,Qa:0,fa:ig_a,Db:ig_2a,Lb:ig_3a,Sb:ig_4a,Ab:ig_5a,Cb:ig_6a,Gb:ig_7a,da:ig_8a,Wa:ig_9a,qb:ig_$a};_IFPC.registerService(_IFPC.Ja,_IFPC.qb);var ig_0={obj:ig_,init:function(a,b){a.onmousedown=ig_0.start;a.obj=b;if(isNaN(parseInt(b.style.left,10)))b.style.left="0px";if(isNaN(parseInt(b.style.top,10)))b.style.top="0px";b.onDragStart=new Function;b.onDragEnd=new Function;b.onDrag=new Function},uninit:function(a,b){window.clearInterval(b.eb);a.onmousedown=ig_;a.obj=ig_;b.onDragStart=ig_;b.onDragEnd=ig_;b.onDrag=ig_},start:function(a){var b=ig_0.obj=this.obj;a=ig_0.fixE(a);if(a.which!=1)return ig_b;b.onDragStart(a);var c=a.clientY;ig_1.$a||
(c+=document.body.scrollTop);b.lastMouseX=a.clientX;b.lastMouseY=c;b.offsetMouseX=parseInt(b.style.left,10)-a.clientX;b.offsetMouseY=parseInt(b.style.top,10)-c;b.eb=window.setInterval(ig_ab(b,document.body.scrollHeight>document.documentElement.clientHeight?document.body.scrollHeight:document.documentElement.clientHeight),10);document.onmouseup=ig_0.end;document.onmousemove=ig_0.drag;return ig_a},drag:function(a){a=ig_0.fixE(a);if(a.which==0)return ig_0.end();var b=ig_0.obj,c=a.clientY;ig_1.$a||(c+=
document.body.scrollTop);var d=a.clientX;if(b.lastMouseX==d&&b.lastMouseY==c)return ig_a;var e=d+b.offsetMouseX,f=c+b.offsetMouseY;b.style.left=e+"px";b.style.top=f+"px";b.lastMouseX=d;b.lastMouseY=c;b.onDrag(e,f);return ig_a},end:function(a){a=ig_0.fixE(a);document.onmousemove=ig_;document.onmouseup=ig_;window.clearInterval(ig_0.obj.eb);var b=ig_0.obj.onDragEnd();ig_0.obj=ig_;return b},fixE:function(a){if(typeof a=="undefined")a=window.event;if(typeof a.layerX=="undefined")a.layerX=a.offsetX;if(typeof a.layerY==
"undefined")a.layerY=a.offsetY;if(typeof a.which=="undefined")a.which=a.button;return a}};function ig_bb(a,b,c){if(!a)return[];var d=b=="*"&&a.all?a.all:a.getElementsByTagName(b),e=[];c=c.replace(/\-/g,"\\-");var f=new RegExp("(^|\\s)"+c+"(\\s|$)"),g;for(var h=0;h<d.length;h++){g=d[h];f.test(g.className)&&e.push(g)}return e}
var _IG_initDrag=function(a,b){ig_1.F=a;ig_1.G=b;ig_1.v=ig_bb(ig_1.F,"div","yui-u");if(_old_html){ig_1.db=ig_1.F.tBodies[0].rows[0];ig_1.v=ig_1.db.cells}ig_1.k=[];var c=0;for(var d=0;d<ig_1.v.length;d++){var e=ig_1.v[d];if(e.className.indexOf("ig_dnd_fixed_col")!=-1||e.style.display=="none")continue;for(var f=0;f<e.childNodes.length;f++){var g=e.childNodes[f];if(g.tagName=="DIV"){ig_1.k[c]=g.className!="dm"?new ig_cb(g):new ig_db(g);c++}}}_IG_AddEventHandler("unload",ig_2)};
function ig_2(){if(ig_1.k)for(var a=0;a<ig_1.k.length;a++){ig_1.k[a].L();ig_1.k[a]=ig_}ig_1.k=ig_;ig_1.v=ig_;if(_old_html)ig_1.db=ig_;ig_1.F=ig_}var ig_1={};ig_1.Ha=navigator.userAgent;ig_1.ta=ig_1.Ha.indexOf("Gecko")!=-1;ig_1.va=ig_1.Ha.indexOf("Opera")!=-1;ig_1.$a=ig_1.Ha.indexOf("Safari")!=-1;ig_1.Ma="IG_pageDivMaskId";ig_1.La="IG_moduleDivMaskId";ig_1.xb=function(){ig_1.F.style.display="none"};ig_1.zb=function(){ig_1.F.style.display=""};ig_1.t=ig_;
ig_1.z=function(){if(!ig_1.t){ig_1.t=document.createElement("DIV");ig_1.t.className="modbox";ig_1.t.backgroundColor="";ig_1.t.style.border="2px dashed #aaa";ig_1.t.innerHTML="&nbsp;"}return ig_1.t};ig_1.m=function(a,b){return function(){return a[b].apply(a,arguments)}};
ig_1.ob=function(){if(ig_1.G){var a=ig_1.G.getElementsByTagName("LI");if(_old_html)a=ig_1.G.tBodies[0].rows[0].cells;for(var b=0;b<a.length;b++){var c=a[b];if(c.className.indexOf("unselectedtab")<0)continue;if(c.style.display=="none")continue;c.isDraggableTo=ig_b;c.pagePosLeft=ig_1.j(c,ig_b);c.pagePosRight=c.pagePosLeft+c.offsetWidth;c.pagePosTop=ig_1.j(c,ig_a);c.pagePosBottom=c.pagePosTop+c.offsetHeight}}};
ig_1.nb=function(a){for(var b=0;b<ig_1.k.length;b++){var c=ig_1.k[b];c.a.pagePosLeft=ig_1.j(c.a,ig_b);c.a.pagePosTop=ig_1.j(c.a,ig_a)}var d=a.a.nextSibling;while(d){d.pagePosTop-=a.a.offsetHeight;d=d.nextSibling}};ig_1.j=function(a,b){var c=0,d=0;if(a&&a.offsetParent&&a.offsetParent.id)if(!b){var e=a.offsetParent.getElementsByTagName(a.tagName);if(e&&e[0])d=e[0].offsetTop}while(a){c+=a["offset"+(b?"Left":"Top")];a=a.offsetParent}return c-d};
ig_1.Na=function(a){ig_1.Da();var b=document.createElement("DIV");b.id=ig_1.Ma;b.innerHTML="&nbsp;";b.style.position="absolute";b.style.width="100%";b.style.height=document.body.offsetHeight+"px";b.style.left="0px";b.style.top="0px";b.style.backgroundImage="url(http://www.google.com/ig/images/cleardot.gif)";b.style.zIndex="9999";document.body.appendChild(b);if(a.Eb){b=b.cloneNode(ig_b);b.id=ig_1.La;b.style.height=a.a.offsetHeight-a.i.offsetHeight+"px";b.style.top=a.i.offsetHeight+"px";a.a.appendChild(b)}};
ig_1.Da=function(){var a=[ig_1.La,ig_1.Ma];for(var b=0;b<a.length;b++){var c=_gel(a[b]);c&&c.parentNode.removeChild(c)}};ig_1.Nb=function(){var a="";for(var b=0;b<ig_1.v.length;b++){var c=ig_1.v[b];for(var d=0;d<c.childNodes.length-1;d++){var e=c.childNodes[d];if(e.tagName=="DIV"){a+=a!=""?":":"";a+=e.id.substring(2)+"_"+c.id.substring(2)}}}_xsetp("mp="+_esc(a))};function ig_db(a){this.L=ig_eb;this.a=a;this.a.innerHTML="<br />"}function ig_eb(){this.a=ig_}
function ig_cb(a){this._urlMouseUp=ig_fb;this._urlMouseDown=ig_gb;this._urlClick=ig_hb;this._dragStart=ig_ib;this._drag=ig_jb;this._dragEnd=ig_kb;this.ia=ig_3;this.V=ig_lb;this.L=ig_4;this.l=ig_a;this.a=a;this.i=_gel(a.id+"_h");this.e=_gel(a.id+"_url");this.Eb=this.a.getElementsByTagName("IFRAME").length>0;this.a.DND_Module=this;if(this.i){this.i.style.cursor="move";ig_0.init(this.i,this.a);this.a.onDragStart=ig_1.m(this,"_dragStart");this.a.onDrag=ig_1.m(this,"_drag");this.a.onDragEnd=ig_1.m(this,
"_dragEnd");if(this.e){this.e.style.cursor="pointer";if(ig_1.ta){this.e.onmousedown=ig_1.m(this,"_urlMouseDown");this.e.onclick=ig_1.m(this,"_urlClick")}else this.e.onmouseup=ig_1.m(this,"_urlMouseUp")}}}function ig_4(){if(this.i){if(this.e){this.e.onclick=ig_;this.e.onmouseup=ig_;this.e=ig_}ig_0.uninit(this.i,this.a);this.a.onDragStart=ig_;this.a.onDrag=ig_;this.a.onDragEnd=ig_;this.i=ig_}this.a=ig_}
function ig_fb(a){a=ig_0.fixE(a);if(this.l||!this.e||!this.e.href||a.which!=1)return ig_b;this.V("titleclick");if(this.e.target||a.shiftKey)window.open(this.e.href,this.e.target);else document.location=this.e.href;return ig_a}function ig_gb(a){a=ig_0.fixE(a);a.stopPropagation();return ig_b}function ig_hb(){if(!this.l&&this.e&&this.e.href){this.V("titleclick");return ig_b}return ig_a}
function ig_ib(){ig_1.nb(this);ig_1.ob();this.origNextSibling=this.a.nextSibling;var a=ig_1.z(),b=this.a.offsetHeight;b-=parseInt(a.style.borderTopWidth,10)*2;var c=this.a.offsetWidth,d=ig_1.j(this.a,ig_b),e=ig_1.j(this.a,ig_a);this.a.style.width=c+"px";a.style.height=b+"px";this.a.parentNode.insertBefore(a,this.a.nextSibling);this.a.style.position="absolute";this.a.style.zIndex=10000;this.a.style.left=d+"px";this.a.style.top=e+"px";ig_1.Na(this);this.l=ig_a;return ig_a}
function ig_5(){var a=0,b=0;if(typeof window.pageYOffset=="number"){a=window.pageXOffset;b=window.pageYOffset}else if(document.body&&(document.body.scrollLeft||document.body.scrollTop)){a=document.body.scrollLeft;b=document.body.scrollTop}else if(document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)){a=document.documentElement.scrollLeft;b=document.documentElement.scrollTop}return[a,b]}
function ig_jb(a,b){if(!this.l){this.a.style.filter="alpha(opacity=50)";this.a.style.opacity=0.5;this.l=ig_b;this.V("dragstart")}var c=ig_,d=100000000;for(var e=0;e<ig_1.k.length;e++){var f=ig_1.k[e],g=a;if(document.body.dir=="rtl"&&f.a.offsetWidth==1)g+=this.a.offsetWidth;var h=Math.sqrt(Math.pow(g-f.a.pagePosLeft,2)+Math.pow(b-f.a.pagePosTop,2));if(f==this)continue;if(isNaN(h))continue;if(h<d){d=h;c=f}}this.r=ig_;if(ig_1.G){var j=ig_1.G.getElementsByTagName("LI");if(_old_html)j=ig_1.G.tBodies[0].rows[0].cells;
for(var e=0;e<j.length;e++){var f=j[e];if(!f.isDraggableTo)continue;var l=ig_5();if(this.a.lastMouseX>=f.pagePosLeft&&this.a.lastMouseX<=f.pagePosRight&&this.a.lastMouseY+l[1]>=f.pagePosTop&&this.a.lastMouseY+l[1]<=f.pagePosBottom){this.r=f;var n=ig_1.z();n.parentNode!=ig_&&n.parentNode.removeChild(n);break}}for(var e=0;e<j.length;e++){var f=j[e];if(f.id.indexOf("view")>=0)if(f==this.r){if(f.className.indexOf(" tab_hover")<0)f.className+=" tab_hover"}else f.className=f.className.replace(/ tab_hover/g,
"")}}var n=ig_1.z();if(this.r==ig_&&c!=ig_&&n.nextSibling!=c.a){c.a.parentNode.insertBefore(n,c.a);if(ig_1.va){document.body.style.display="none";document.body.style.display=""}}}function ig_kb(){ig_1.Da();this.ia()&&ig_1.Nb();if(this.r){var a=this.r.id.match(/tab(\d+)_/)[1],b=this.a.id.match(/m_(\d+)/)[1];_xsetp("mt="+b+":"+a);this.a.style.display="none";this.r.className=this.r.className.replace(/ tab_hover/g,"")}_hideNewUserTip();this.l&&this.V("dragend");return ig_b}
function _hideNewUserTip(){var a=_gel("new_user_tip");if(a)a.style.display="none";var b=_gel("new_user_save");if(b)b.style.display="block"}
function ig_3(){var a=ig_a;this.a.style.position="";this.a.style.width="";this.a.style.zIndex="";this.a.style.filter="";this.a.style.opacity="";window.scrollBy(0,0);var b=ig_1.z();if(b.parentNode!=ig_){if(b.nextSibling!=this.origNextSibling){b.parentNode.insertBefore(this.a,b.nextSibling);a=ig_b}b.parentNode.removeChild(b)}if(ig_1.va){document.body.style.display="none";document.body.style.display=""}return a}
function ig_lb(a){switch(a){case "titleclick":_IG_TriggerModuleEvent(this.a.id,a,this.e.href);_IG_TriggerEvent("module"+a,this.a.id,this.e.href);break;case "dragstart":case "dragend":_IG_TriggerDelayedModuleEvent(this.a.id,a);_IG_TriggerDelayedEvent("module"+a,this.a.id);break}}
function ig_ab(a,b){return function(){var c=ig_mb(),d=ig_5(),e=d[1],f=4,g=0.05*c,h=e,j=a.offsetTop;if(a.lastMouseY<=g){j=a.offsetTop-f;h=e-f}else if(a.lastMouseY>=c-g){j=Math.min(b-a.offsetHeight,a.offsetTop+f);h=Math.min(b-c,e+f)}var l=h-e;if(l!=0){window.scrollBy(0,l);a.style.top=j+"px"}}}
function ig_mb(){var a;a=window.innerHeight?window.innerHeight:document.documentElement&&document.documentElement.clientHeight?document.documentElement.clientHeight:document.body.offsetHeight;if(a<document.body.clientHeight)return a;return document.body.clientHeight}_IG_AddCustomEventHandler("initdrag",function(a,b){_IG_initDrag(a,b)});function ig_nb(a){var b=_gel("mobile_screen");b.insertBefore(a,b.firstChild);a.style.display="block";var c=ig_ob(a.id),d=_gel("m_"+c);_gel("added_m_"+c).style.display="";_gel("add_m_"+c).style.display="none";d.style.filter="alpha(opacity=30)";d.style.opacity=0.3;if(!ig_1.ta)d.style.width="100%"}function _addToMobileDisplayAndLog(a){ig_nb(a);ig_1.Ea("add")}function _delFromMobileAndLog(a,b,c){ig_pb(a,b,c);ig_1.Ea("del")}
function ig_pb(a){var b=_gel("mobile_m_"+a),c=_gel("m_"+a);b.style.display="none";if(c){c.style.filter="alpha(opacity=100)";c.style.opacity=1;var d=_gel("add_"+c.id),e=_gel("added_"+c.id);e.style.display="none";d.style.display=""}}function ig_ob(a){if(a.indexOf("mobile")==0)return a.substring("mobile_m_".length);return a.substring("m_".length)}function ig_qb(){for(var a=0;a<ig_1.n.length;a++){ig_1.n[a].L();ig_1.n[a]=ig_}ig_1.n=ig_}
ig_1.mb=function(a){for(var b=0;b<ig_1.n.length;b++){var c=ig_1.n[b];c.a.pagePosLeft=ig_1.j(c.a,ig_b);c.a.pagePosTop=ig_1.j(c.a,ig_a)}var d=a.a.nextSibling;while(d){d.pagePosTop-=a.a.offsetHeight;d=d.nextSibling}};ig_1.Ea=function(a){var b="",c=_gel("mobile_screen");for(var d=0;d<c.childNodes.length;d++){var e=c.childNodes[d];if(e.style.display!="none"){b+=b!=""?":":"";b+=e.id.substring(9)}}_xsetp("mobile_mp="+_esc(b)+"&action="+_esc(a))};
function ig_rb(a){this._dragStart=ig_sb;this._drag=ig_tb;this._dragEnd=ig_ub;this.L=ig_4;this.ia=ig_3;this.l=ig_a;this.a=a;this.a.style.cursor="move";this.i=_gel(a.id+"_h");this.Pa=_gel(a.id+"_b");this.i&&ig_0.init(this.i,this.a);this.Pa&&ig_0.init(this.Pa,this.a);this.a.onDragStart=ig_1.m(this,"_dragStart");this.a.onDrag=ig_1.m(this,"_drag");this.a.onDragEnd=ig_1.m(this,"_dragEnd")}
function ig_sb(){ig_1.mb(this);this.origNextSibling=this.a.nextSibling;var a=ig_1.z(),b=this.a.offsetHeight;if(ig_1.ta)b-=parseInt(a.style.borderTopWidth,10)*2;a.className="";var c=this.a.offsetWidth,d=ig_1.j(this.a,ig_b),e=ig_1.j(this.a,ig_a);ig_1.xb();this.a.style.width=c+"px";a.style.height=b+"px";this.a.parentNode.insertBefore(a,this.a.nextSibling);this.a.style.position="absolute";this.a.style.zIndex=100;this.a.style.left=d+"px";this.a.style.top=e+"px";ig_1.zb();ig_1.Na(this);this.l=ig_a;return ig_a}
function ig_tb(a,b){if(!this.l){this.a.style.filter="alpha(opacity=70)";this.a.style.opacity=0.7;this.l=ig_b}var c=ig_,d=100000000;for(var e=0;e<ig_1.n.length;e++){var f=ig_1.n[e],g=Math.sqrt(Math.pow(a-f.a.pagePosLeft,2)+Math.pow(b-f.a.pagePosTop,2));if(f==this)continue;if(isNaN(g))continue;if(g<d){d=g;c=f}}var h=ig_1.z();h.className="";if(c!=ig_&&h.nextSibling!=c.a){c.a.parentNode.insertBefore(h,c.a);if(ig_1.va){document.body.style.display="none";document.body.style.display=""}}}
function ig_ub(){ig_1.Da();this.ia()&&ig_1.Ea("move");return ig_b}var _IG_initMobileDrag=function(a){ig_1.F=a;ig_1.n=[];var b=0,c=_gel("mobile_screen").childNodes;for(var d=0;d<c.length;d++){var e=c[d];if(e.tagName=="DIV"){ig_vb(e)&&ig_wb(e);ig_1.n[b]=new ig_rb(e);b++}}_IG_AddEventHandler("unload",ig_qb)};function ig_vb(a){var b=_gel(a.id+"_h");if(b){var c=_gel(a.id+"_h").innerHTML;if(c.indexOf("Google Reader")>=0)return ig_b}}
function ig_wb(a){var b=_gel(a.id+"_b");for(var c=0;c<b.childNodes.length;c++){var d=b.childNodes[c];if(d.tagName=="TABLE")d.className="mmc"}};function _delpromobox(){_xsetp("hp=0");var a=_gel("promobox");a.parentNode.removeChild(a);return ig_a}function _delmessage(){_xsetp("gm=0");var a=_gel("googlemessage");a.parentNode.removeChild(a);return ig_a}function _delpromomod(){_xsetp("pm=0");var a=_gel("promomod");a.parentNode.removeChild(a);return ig_a};function ig_6(a){var b=_gel("remote_iframe_"+a);if(!b)return;b.src=_IG_Prefs._updatePrefsInUrl(a,b.src)}var _IG_iFrameTransitionStrategy=function(a,b,c){this.b=a;this.I=b;this.Ta="";this.ea=c||"800px";this.ca=ig_;this.Va=ig_;this.Ua=ig_};_IG_iFrameTransitionStrategy.prototype._onPreDetachDashboard=function(){var a=_gel("remote_iframe_"+this.b);this.Ta=a.src};
_IG_iFrameTransitionStrategy.prototype._onPreAttachMaximized=function(){_gel("m_"+this.b);var a=_gel("m_"+this.b+"_b");a.className="modboxin_max";ig_7.removeRoundedCorners(this.b);_gel("rcam_t1").className="rnd1_max_top";_gel("rcam_t2").className="rnd2_max_top";_gel("rcam_t3").className="rnd3_max_top"};
_IG_iFrameTransitionStrategy.prototype._onPreAttachDashboard=function(){var a=_gel("m_"+this.b),b=_gel("m_"+this.b+"_b"),c=/_e/.test(a.className)?"_e":"";a.className="modbox"+c;b.className="modboxin";ig_7.restoreRoundedCorners(this.b);_gel("rcam_t1").className="rnd1";_gel("rcam_t2").className="rnd2";_gel("rcam_t3").className="rnd3"};
_IG_iFrameTransitionStrategy.prototype._onPostAttachMaximized=function(){var a=_gel("remote_iframe_"+this.b),b=_gel("m_"+this.b),c=_gel("m_"+this.b+"_b");this.Va=b.style.height;this.Ua=c.style.height;this.ca=a.style.height;a.src=this.I;a.style.height=this.ea;ig_6(this.b)};
_IG_iFrameTransitionStrategy.prototype._onPostAttachDashboard=function(){var a=_gel("remote_iframe_"+this.b),b=_gel("m_"+this.b),c=_gel("m_"+this.b+"_b");if(this.ca!=ig_){a.style.height=this.ca;b.style.height=this.Va;c.style.height=this.Ua}a.src=this.Ta;ig_6(this.b)};var _IG_inlinedTransitionStrategy=function(a,b,c,d){this.b=a;this.ab=ig_a;this.I=b;this.ga="max_div";this.P="max_iframe";this.ea=c||"800px";this.Tb=d||ig_a;this.Aa=ig_;this.Ba=ig_};
_IG_inlinedTransitionStrategy.prototype._updateIframeSrc=function(a){this.I=a;var b=_gel(this.P);if(b)b.src=a};_IG_inlinedTransitionStrategy.prototype._setNextMaxIframeAddress=function(a){this.I=a};_IG_inlinedTransitionStrategy.prototype._setPostMaximizeCallback=function(a){if(!a||typeof a=="function")this.Aa=a};_IG_inlinedTransitionStrategy.prototype._setPostRestoreCallback=function(a){if(!a||typeof a=="function")this.Ba=a};
_IG_inlinedTransitionStrategy.prototype._onresizeHandler=function(){var a=_gel("max_iframe"),b=_gel("max_div"),c;a.style.width="200px";c=_IG_isIE()?b.scrollWidth-25:b.offsetWidth;c=Math.max(200,c);a.style.width=c+"px"};
_IG_inlinedTransitionStrategy.prototype._onPostAttachMaximized=function(){var a=_gel(this.ga),b=_gel(this.P),c=_gel("m_"+this.b+"_b");if(!a){a=document.createElement("DIV");a.id=this.ga}if(!b){b=document.createElement("IFRAME");b.frameBorder="0";b.scrolling="no";b.style.border="0";b.style.margin="0";b.style.padding="0";b.style.overflow="hidden";b.style.width="100%";b.id=this.P;a.appendChild(b)}if(this.Tb)_IG_AddEventHandler("resize",this._onresizeHandler);else{_IG_RemoveEventHandler("resize",this._onresizeHandler);
b.style.width="100%"}c.nextSibling?c.parentNode.insertBefore(a,c.nextSibling):c.parentNode.appendChild(a);a.className="modboxin_max";a.style.display="";b.style.height=this.ea;b.src=_IG_Prefs._updatePrefsInUrl(this.b,this.I);this.Aa&&this.Aa(this);return b.src};_IG_inlinedTransitionStrategy.prototype._onPostAttachDashboard=function(){var a=_gel(this.ga);a.style.display="none";var b=_gel(this.P);b.src="";this.Ba&&this.Ba(this);return b.src};
_IG_inlinedTransitionStrategy.prototype._onPreAttachMaximized=function(){_gel("m_"+this.b);var a=_gel("m_"+this.b+"_b");a.className="modboxin_max";ig_7.removeRoundedCorners(this.b);_gel("rcam_t1").className="rnd1_max_top";_gel("rcam_t2").className="rnd2_max_top";_gel("rcam_t3").className="rnd3_max_top"};
_IG_inlinedTransitionStrategy.prototype._onPreAttachDashboard=function(){var a=_gel("m_"+this.b),b=_gel("m_"+this.b+"_b"),c=/_e/.test(a.className)?"_e":"";a.className="modbox"+c;b.className="modboxin";ig_7.restoreRoundedCorners(this.b);window.onresize=ig_;_gel("rcam_t1").className="rnd1";_gel("rcam_t2").className="rnd2";_gel("rcam_t3").className="rnd3"};var _IG_scaleInlinedTransitionStrategy=function(a){this.b=a;this.ab=ig_a};
_IG_scaleInlinedTransitionStrategy.prototype._onPostAttachMaximized=function(){var a=_gel("m_"+this.b+"_b");a.style.display="block"};_IG_scaleInlinedTransitionStrategy.prototype._onPreAttachMaximized=_IG_iFrameTransitionStrategy.prototype._onPreAttachMaximized;_IG_scaleInlinedTransitionStrategy.prototype._onPreAttachDashboard=_IG_iFrameTransitionStrategy.prototype._onPreAttachDashboard;var _IG_noMaxSupportTransitionStrategy=function(a,b){this.b=a;this.ab=ig_a;this.Ga=b};
_IG_noMaxSupportTransitionStrategy.prototype._onPreDetachDashboard=function(){};function _IG_noMaxSupportResizeIframe(a){var b=window.innerHeight;if(document.body.clientHeight)b=document.body.clientHeight;_gel(a).style.height=parseInt(b-_gel(a).offsetTop-8,ig_)+"px"}_IG_noMaxSupportTransitionStrategy.prototype._onPostAttachDashboard=function(){ig_6(this.b)};
_IG_noMaxSupportTransitionStrategy.prototype._onPostAttachMaximized=function(){var a=_gel("m_"+this.b),b=_gel("mu_div");if(b==ig_){b=document.createElement("DIV");b.id="mu_div";var c=["<table border=0 height=100% width=100%>",'<tr valign=top><td width="450px" height=100%>','<div id="muph"></div><br>',"</td><td height=100%>",'<div style="padding-top:4px;padding-left:4px;">','<b class="rnd_modtitle">','<b class="rnd1"></b><b class="rnd2"></b><b class="rnd3"></b></b>','<div class="modtitle">You might also like...</div>',
"</div>",'<iframe id="max_ifr2" ',"onload=\"_IG_noMaxSupportResizeIframe('max_ifr2')\" ",'frameBorder=0 scrolling="no" style="height:100%; border:0px" ','width="100%"></iframe></td></tr></table>'];b.innerHTML=c.join("")}a.parentNode.replaceChild(b,a);var d=_gel("muph");d.appendChild(a);b.style.display="";a.style.minWidth="300px";var e=_gel("max_ifr2");if(this.Ga&&this.Ga.length){if(e)e.src="/ig/directory?output=brief&recommend="+this.Ga}else if(e)e.src="";ig_6(this.b)};
_IG_noMaxSupportTransitionStrategy.prototype._onPreDetachMaximized=function(){var a=_gel("m_"+this.b),b=_gel("mu_div");if(b){b.parentNode.replaceChild(a,b);b.style.display="none"}a.style.minWidth=""};var ig_xb=" modhover",ig_yb="titlehover";function _IG_hoverModule(a,b){var c=_gel("m_"+a);ig_8(a,b,c,ig_xb)}function _IG_hoverHeader(a,b){var c=_gel("m_"+a+"_drag");c.style.display=b?"":"none";var d=_gel("m_"+a+"_home_menu");ig_8(a,b,d,ig_yb)}function ig_8(a,b,c,d){if(b){var e=ig_7.isModuleMaximized(a);if(!e&&c.className.indexOf(d)==-1)c.className+=d}else c.className=c.className.replace(RegExp(d),"")};var ig_7=new (function(){this.Z="modules";this.Y="dash_ph";this.W="max_ph";this.g=ig_;this.Xa="";this.Za=ig_;if(window.onbeforeunload){var a=window.onbeforeunload;window.onbeforeunload=function(){a();ig_7.onCommitServerState()}}else window.onbeforeunload=function(){ig_7.onCommitServerState()}});ig_7._getCurrentMaxId=function(){return ig_7.g};ig_7.onCommitServerState=function(){if(this.g!=this.Za){var a=ig_f(),b="/ig/setp?et="+_et+"&maxm="+(this.g?this.g:"-1");a.open("GET",b,ig_a);a.send(ig_)}};
ig_7.setInitialMaximizedModuleId=function(a){this.Za=a};ig_7.setExperimentName=function(a){this.Xa=a};ig_7.swapMaximizedModule=function(a){if(!(this.g==a))if(this.g){this.restoreModule(this.g);this.maximizeModule(a)}else this.maximizeModule(a)};ig_7.restoreView=function(){this.g&&this.restoreModule(this.g)};ig_7.isModuleMaximized=function(a){return this.g==a};ig_7.getStrategy=function(a){var b=_max_strategies[a];if(b==ig_){b=new _IG_noMaxSupportTransitionStrategy(a);_max_strategies[a]=b}return b};
ig_7.maximizeModule=function(a){var b=this.getStrategy(a);b._onPreDetachDashboard&&b._onPreDetachDashboard();this.ub(a);b._onPostDetachDashboard&&b._onPostDetachDashboard();b._onPreAttachMaximized&&b._onPreAttachMaximized();this.lb(a);b._onPostAttachMaximized&&b._onPostAttachMaximized();this.g=a};
ig_7.restoreModule=function(a){var b=this.getStrategy(a);b._onPreDetachMaximized&&b._onPreDetachMaximized();this.vb(a);b._onPostDetachMaximized&&b._onPostDetachMaximized();b._onPreAttachDashboard&&b._onPreAttachDashboard();this.kb(a);b._onPostAttachDashboard&&b._onPostAttachDashboard();this.g=ig_};ig_7.Ob=function(a){this.Ca=function(){_IG_minimize_view(a,"delete",this.Xa)};_IG_AddModuleEventHandler(a,"delete",this.Ca)};ig_7.rb=function(a){this.Ca&&_IG_RemoveModuleEventHandler(a,"delete",this.Ca)};
ig_7.ub=function(a){var b=_gel(this.Y);if(b==ig_){b=document.createElement("DIV");b.id=this.Y;b.style.display="none"}var c=_gel("m_"+a),d=_gel(this.Z).parentNode;c.parentNode.replaceChild(b,c);d.appendChild(c);b.style.display="block";b.style.height=c.clientHeight+"px";this.Ra(a)};
ig_7.lb=function(a){var b=_gel(this.W);if(b==ig_){b=document.createElement("DIV");b.id=this.W;b.style.display="none"}var c=_gel("m_"+a),d=_gel(this.Z);b.appendChild(c);d.parentNode.appendChild(b);d.style.display="none";b.style.display="block";c.className=c.className.replace(/( |^)modbox( |$)/,"$1modbox_max$2");this.wb(a);this.Ob(a);_IG_TriggerEvent("modulemaximize",a);_IG_TriggerModuleEvent(a,"maximize")};
ig_7.vb=function(a){var b=_gel(this.Z),c=_gel(this.W);c.style.display="";b.style.display="";var d=_gel("m_"+a);d.className=d.className.replace(/modbox_max/,"modbox");this.Ra(a)};ig_7.kb=function(a){var b=_gel(this.Y),c=_gel("m_"+a);b.parentNode.replaceChild(c,b);b.style.display="none";this.yb(a);this.rb(a);_IG_TriggerEvent("moduleunmaximize",a);_IG_TriggerModuleEvent(a,"unmaximize")};
ig_7.wb=function(a){var b=_gel("m_"+a),c=_gel("m_"+a+"_h");b.parentNode.className+=" ig_dnd_fixed_col";c.style.cursor="default";ig_2()};ig_7.yb=function(a){var b=_gel("m_"+a),c=_gel("m_"+a+"_h");b.parentNode.className=b.parentNode.className.replace(/ ig_dnd_fixed_col/,"");c.style.cursor="move";_IG_initDrag(_table,_tabs)};ig_7.Ra=function(a){_IG_hoverModule(a,ig_a);_IG_hoverHeader(a,ig_a)};
ig_7.Ya=function(a){var b=_gel(a),c=b.childNodes,d=[];for(var e=0;e<c.length;++e)if(c[e].className&&(c[e].className.indexOf("rnd_modtitle")==0||c[e].className.indexOf("rnd_modboxin")==0))for(var f=0;f<c[e].childNodes.length;++f)d[d.length]=c[e].childNodes[f];return d};ig_7.removeRoundedCorners=function(a){var b=this.Ya("m_"+a);for(var c=0;c<b.length;++c)b[c].className+="_max"};
ig_7.restoreRoundedCorners=function(a){var b=this.Ya("m_"+a);for(var c=0;c<b.length;++c)b[c].className=b[c].className.replace(/_max/,"")};
var _IG_maximize_persistent_module=function(a,b){ig_7.setInitialMaximizedModuleId(a);_IG_maximize_view(a,"persist",b)},_IG_toggle_view=function(a){ig_7.swapMaximizedModule(a)},_IG_is_maximized_module=function(a){return ig_7.isModuleMaximized(a)},_IG_maximize_view=function(a,b,c){if(b==ig_)b="dunno";_sendx("/ig/ui?xp="+c+"&action=maximizeMod&from="+b+"&m="+a,ig_,ig_a,ig_);if(!ig_7.isModuleMaximized(a)){ig_7.setExperimentName(c);ig_7.swapMaximizedModule(a)}},_IG_minimize_view=function(a,b,c){if(b==
ig_)b="dunno";_sendx("/ig/ui?xp="+c+"&action=minimizeMod&from="+b+"&m="+a,ig_,ig_a,ig_);ig_7.isModuleMaximized(a)&&ig_7.restoreModule(a)},_IG_restore_view=function(){ig_7.restoreView()};_exportClass("gadgets.views","ViewManager",ig_7,ig_,["isModuleMaximized",ig_7.isModuleMaximized,"getCurrentMaxId",ig_7._getCurrentMaxId]);var _IG_Json=ig_Z;var _IG_ViewType={FULL_PAGE:"canvas",DASHBOARD:"home",POPUP:"POPUP"},_IG_View=function(a,b){this.Jb=a;this.Hb=!!b};_IG_View.prototype.pa=function(){return this.Jb};_IG_View.prototype.ua=function(){return this.Hb};var _IG_SupportedViews={};_IG_SupportedViews.FULL_PAGE=new _IG_View(_IG_ViewType.FULL_PAGE,ig_b);_IG_SupportedViews.canvas=new _IG_View(_IG_ViewType.FULL_PAGE,ig_b);_IG_SupportedViews.DASHBOARD=new _IG_View(_IG_ViewType.DASHBOARD,ig_a);
_IG_SupportedViews.home=new _IG_View(_IG_ViewType.DASHBOARD,ig_a);function _navigateto(a,b,c){if(b==_IG_ViewType.FULL_PAGE)_IG_is_maximized_module(a)||_IG_maximize_view(a,"navTo","");else _IG_is_maximized_module(a)&&_IG_minimize_view(a,"navTo","");if(c){var d=_IG_Json.stringify(c);_gel("remote_iframe_"+a).src+="&view-params="+_esc(d)}return ig_b}function _IG_NavigateToGadget(a,b,c){_navigateto(a,b,c)}
function _getCurrentView(a){return _IG_is_maximized_module(a)?_IG_SupportedViews.FULL_PAGE:_IG_SupportedViews.DASHBOARD}function _IG_GetCurrentView(a){return _getCurrentView(a)}function _getParams(a){var b=_gel("remote_iframe_"+a).src,c=_argsUrl(b),d=_IG_Json.parse(_unesc(c["view-params"]));return d}function _IG_GetViewParams(a){return _getParams(a)}function _IG_GetSupportedViews(){return _IG_SupportedViews}
_exportSymbols("gadgets.views",["ViewType",_IG_ViewType,"getSupportedViews",_IG_GetSupportedViews,"requestNavigateTo",_IG_NavigateToGadget,"getCurrentView",_IG_GetCurrentView,"getParams",_IG_GetViewParams]);_exportClass("gadgets.views","View",_IG_View,["getName",_IG_View.prototype.pa,"isOnlyVisibleGadget",_IG_View.prototype.ua]);var ig_9=new (function(){this.J={};var a=window.onbeforeunload;window.onbeforeunload=function(){a&&a();ig_9.Ib()}});ig_9.jb=function(a,b){this.J[a]=b};ig_9.Mb=function(a){delete this.J[a]};ig_9.B=function(a){return this.J[a]};ig_9.Ib=function(){var a=[];for(var b in this.J)a.push(b+"="+this.J[b]);if(a.length){var c=ig_f(),d="/ig/setp?et="+_et+"&"+a.join("&");c.open("GET",d,ig_a);c.send(ig_)}};
var _IG_add_setp_parameter_onbeforeunload=function(a,b){ig_9.jb(a,b)},_IG_remove_setp_parameter_onbeforeunload=function(a){ig_9.Mb(a)},_IG_get_setp_parameter_onbeforeunload=function(a){return ig_9.B(a)};var ig_$=(function(){var a=ig_,b=ig_,c=ig_a,d={},e={},f=ig_b,g=ig_,h=ig_,j=ig_;function l(){var k=[],i=[];for(var m in e)if(e[m]&&!d[m])k.push(m);else!e[m]&&d[m]&&i.push(m);k.length?_IG_add_setp_parameter_onbeforeunload("exptabs",k.join(":")):_IG_remove_setp_parameter_onbeforeunload("exptabs");i.length?_IG_add_setp_parameter_onbeforeunload("coltabs",i.join(":")):_IG_remove_setp_parameter_onbeforeunload("coltabs");_IG_add_setp_parameter_onbeforeunload("roster",f+"")}function n(k){_gel("gadget_set"+
k).style.display="block";_gel("triangle"+k).className="v2minbox";e[k]=ig_b;_sendx("/ig/ui?xp=v2&action=expandTab&t="+k,ig_,ig_a,ig_)}function o(k){_gel("gadget_set"+k).style.display="none";_gel("triangle"+k).className="v2maxbox";e[k]=ig_a;_sendx("/ig/ui?xp=v2&action=collapseTab&t="+k,ig_,ig_a,ig_)}function p(){if(!h){h=document.createElementNS("http://www.w3.org/2000/svg","svg");h.setAttribute("width","36")}if(!j){j=document.createElementNS("http://www.w3.org/2000/svg","text");j.setAttribute("transform",
"rotate(270)");j.setAttribute("lengthAdjust","spacingAndGlyphs");j.setAttribute("font-weight","bold");j.setAttribute("text-anchor","middle")}}function r(){var k=_gel("full_nav"),i=_gel("vert_nav"),m=_gel("col1_contents"),q=_gel("footerwrap"),t=_gel("left_nav_btn");if(k)k.style.display="none";if(i)i.style.display="";if(m&&m.className)m.className=m.className.replace("colwidth","colwidth_vert");if(q)q.className="vert_nav";if(t)t.src="/ig/images/left_nav_expand_btn.png";_xsetp("dfln=false")}function s(){var k=
_gel("full_nav"),i=_gel("vert_nav"),m=_gel("col1_contents"),q=_gel("footerwrap"),t=_gel("left_nav_btn");if(k)k.style.display="";if(i)i.style.display="none";if(m&&m.className)m.className=m.className.replace("_vert","");if(q)q.className="";if(t)t.src="/ig/images/left_nav_collapse_btn.png";_xsetp("dfln=true")}return{setSelectedTabId:function(k){a=k},setNextTabId:function(){var k=_gel("section"+a+"_contents").nextSibling;while(k){if(k.id&&k.id.match(/section\d+_contents/)){b=k.id.match(/\d+/);break}k=
k.nextSibling}},setZipMessage:function(k){g=k},highlightModule:function(k){var i=_gel("section"+a+"_contents");i.className="section_contents leftunselectedtab leftborder";_gel("tab"+a).className="section_title unselected_section_title";var m=_gel("left_nav_m_"+k+"_title");m.className="selected_gadget_title gadget_title leftselectedtab surroundborder";var q=_gel("gadget_set"+a);q.insertBefore(i.previousSibling,m);q.insertBefore(i.nextSibling,m.nextSibling);_gel("tab_separator"+a).style.display="";
if(b)_gel("tab_separator"+b).style.display="";else if(_gel("tab_separator_bot"))_gel("tab_separator_bot").style.display=""},highlightSelectedTab:function(k){var i=_gel("section"+a+"_contents");i.className="selected_section_contents leftselectedtab surroundborder";_gel("tab"+a).className="section_title selected_section_title";var m=_gel("left_nav_m_"+k+"_title");m.className="gadget_title";_gel("tab_separator"+a).style.display="none";if(b)_gel("tab_separator"+b).style.display="none";else if(_gel("tab_separator_bot"))_gel("tab_separator_bot").style.display=
"none";_gel("gadget_set"+a);i.parentNode.insertBefore(m.previousSibling,i);i.parentNode.insertBefore(m.nextSibling,i.nextSibling)},swapHeaderToCanvasMenu:function(k){var i=_gel("m_"+k+"_home_menu");if(i)i.style.display="none";var m=_gel("m_"+k+"_canvas_menu");if(m)m.style.display=""},swapHeaderToHomeMenu:function(k){var i=_gel("m_"+k+"_canvas_menu");if(i)i.style.display="none";var m=_gel("m_"+k+"_home_menu");if(m)m.style.display=""},hideLeftNavModuleTitle:function(k){var i=_gel("left_nav_"+k+"_title");
if(i)i.style.display="none"},showLeftNavModuleTitle:function(k){var i=_gel("left_nav_"+k+"_title");if(i)i.style.display=""},maybeUnzipModule:function(k){var i=_gel("m_"+k+"_b");c=i&&i.style.display=="none";var m=!_gel("remote_iframe_"+k),q=!(_max_strategies[k]instanceof _IG_noMaxSupportTransitionStrategy);i.style.display=m&&q?"none":""},maybeZipModule:function(k){var i=_gel("m_"+k+"_b");i.style.display=c?"none":""},showRoundedCornerOnload:function(){if(a!="0"){_gel("rcbg").style.display="";_gel("col2").className=
"botborder"}},showRoundedCornerOnMaximize:function(){if(a=="0"){_gel("rcbg").style.display="";_gel("col2").className="botborder"}},hideRoundedCornerOnRestore:function(){if(a=="0"){_gel("rcbg").style.display="none";_gel("col2").className="topbotborder"}},expandTabOnLoad:function(k){d[k]=ig_b;e[k]=ig_b},collapseTabOnLoad:function(k){d[k]=ig_a;e[k]=ig_a},toggleTab:function(k,i){if(!k)var k=window.event;k.cancelBubble=ig_b;k.stopPropagation&&k.stopPropagation();_gel("gadget_set"+i).style.display=="none"?
n(i):o(i);l()},toggleRoster:function(){if(!_gel("talk_container"))return;f=!f;_gel("roster_triangle").className=f?"v2minbox":"v2maxbox";if(window.gTalkNotifier&&window.gTalkNotifier._setRosterExpanded)window.gTalkNotifier._setRosterExpanded(f);else _gel("talk_container").style.display=f?"":"none";l()},rosterStateOnload:function(k){f=k},hidePromo:function(k){var i=_gel(k);if(i)i.style.display="none"},swapZipMessage:function(k){var i;for(var m=_gel("DD_"+k).firstChild;m;m=m.nextSibling)if(m.innerHTML&&
(m.innerHTML.match(g[0])||m.innerHTML.match(g[1]))){i=m;break}var q=_gel("m_"+k+"_b"),t=q&&q.style.display=="none";if(i)i.innerHTML=t?g[0]:g[1]},swapRoundedCornerClassNameOnZip:function(k){var i=_gel("m_"+k+"_b"),m=i&&i.style.display=="none",q=i.nextSibling;if(q&&q.className)q.className=m?"rnd_modtitle":"rnd_modboxin"},toggleFullLeftNav:function(){var k=_gel("full_nav");k&&k.style.display=="none"?s():r()},generateVerticalTabSVG:function(k,i,m){if(!h||!j)p();var q=h.cloneNode(ig_b),t=j.cloneNode(ig_b);
t.textContent=k;var u=_gel("findLen");if(!u)return;u.innerHTML=k;var v=u.offsetWidth;q.setAttribute("viewBox","0 0 36 "+(v+20));q.setAttribute("height",v+20);t.setAttribute("x",-(v+20)/2);t.setAttribute("textLength",v);t.setAttribute("y","16");if(m)t.setAttribute("class","selected_section_title_vert");else{q.setAttribute("onclick",'_select_tab_and_log("'+i+'","");');t.setAttribute("class","unselected_section_title_vert");t.setAttribute("text-decoration","underline")}q.appendChild(t);var w=_gel("vert_nav_tab"+
i);w&&w.appendChild(q)}}})(),_IG_LN_init=function(){_IG_AddEventHandler("modulemaximize",ig_$.highlightModule);_IG_AddEventHandler("modulemaximize",ig_$.swapHeaderToCanvasMenu);_IG_AddEventHandler("modulemaximize",ig_$.maybeUnzipModule);_IG_AddEventHandler("modulemaximize",ig_$.showRoundedCornerOnMaximize);_IG_AddEventHandler("moduleunmaximize",ig_$.highlightSelectedTab);_IG_AddEventHandler("moduleunmaximize",ig_$.swapHeaderToHomeMenu);_IG_AddEventHandler("moduleunmaximize",ig_$.maybeZipModule);_IG_AddEventHandler("moduleunmaximize",
ig_$.hideRoundedCornerOnRestore);_IG_AddEventHandler("moduledelete",ig_$.hideLeftNavModuleTitle);_IG_AddEventHandler("moduleundelete",ig_$.showLeftNavModuleTitle);_IG_AddEventHandler("modulezip",ig_$.swapZipMessage);_IG_AddEventHandler("modulezip",ig_$.swapRoundedCornerClassNameOnZip);_IG_AddEventHandler("moduleunzip",ig_$.swapZipMessage);_IG_AddEventHandler("moduleunzip",ig_$.swapRoundedCornerClassNameOnZip);_IG_RegisterOnloadHandler(ig_$.setNextTabId);_IG_RegisterOnloadHandler(ig_$.showRoundedCornerOnload)},
_IG_set_selected_tab_id=ig_$.setSelectedTabId,_IG_expand_tab_onload=ig_$.expandTabOnLoad,_IG_collapse_tab_onload=ig_$.collapseTabOnLoad,_IG_toggle_tab=ig_$.toggleTab,_IG_toggle_roster=ig_$.toggleRoster,_IG_roster_state_onload=ig_$.rosterStateOnload,_IG_hide_promo=ig_$.hidePromo,_IG_set_zip_msg=ig_$.setZipMessage,_IG_toggle_full_left_nav=ig_$.toggleFullLeftNav,_IG_generate_vertical_tab_svg=ig_$.generateVerticalTabSVG;
