<?

$sLangCategory = 'Gorpus Profile Theme';

$aLangContent = array(
	'qwe_profile_theme_top_menu_item' => 'Profile Theme',
	'qwe_profile_theme_form_css_body' => 'CSS Body',
	'qwe_profile_theme_editing' => 'Profile Theme',
	'qwe_profile_theme_form_themes_collection' => 'Themes Collection',
	'qwe_profile_theme_use_theme_code' => 'Load Selected Theme Code',
	'qwe_profile_theme_form_apply_code' => 'Save Profile Theme Code',
	'qwe_profile_theme_theme_not_selected' => 'Theme Not Selected',
	'qwe_profile_theme_form_preview_theme' => 'Preview Profile',
	'qwe_profile_theme_saved' => 'Profile Theme Saved',
	'qwe_profile_theme_chenage_theme' => 'Change Profile Theme',
	'qwe_profile_theme_got_to_profile' => 'View Your Profile',
	'qwe_profile_theme_form_reset_theme' => 'Reset Profile Theme To Default',
	'qwe_profile_theme_is_empty' => 'Profile Theme Is Reset To Default',
	'qwe_profile_theme_sure_reset' => 'Are You Sure To Reset Your Profile Theme To Default?',
	'qwe_profile_theme_form_theme_type' => 'Theme Type',
	'qwe_profile_theme_form_theme_type_myspace' => 'MySpace Layout',
	'qwe_profile_theme_form_theme_type_other' => 'Other',
	'qwe_profile_theme_admin_menu' => 'Profile Themes',
	'qwe_profile_theme_adm' => 'Profile Themes Management',
	'qwe_profile_theme_adm_add' => 'Add New Theme',
	'qwe_profile_theme_adm_manage' => 'Manage Themes',
	'qwe_profile_theme_adm_delete' => 'Delete Theme',
	'qwe_profile_theme_adm_add_theme' => 'Add New Theme',
	'qwe_profile_theme_adm_name' => 'Theme Name',
	'qwe_profile_theme_adm_title' => 'Theme Title',
	'qwe_profile_theme_adm_thumb' => 'Thumbnail',
	'qwe_profile_theme_adm_added' => 'New Profile Theme Added',
	'qwe_profile_theme_add_form_must_be_filled' => 'All Fields Must Be Filled',
	'qwe_profile_theme_add_form_file_upload_error' => 'Thumbnail Upload Error',
	'qwe_profile_theme_add_check_dir_permissions' => 'Thumbnail Upload Error<br />Check data Directory Permissions<br />Should Be 777',
	'qwe_profile_theme_form_restore_current' => 'Restore Current Theme Code',
	'qwe_profile_theme_sure_restore_current' => 'Are You Sure To Restore Your Current Profile Theme Code?',
	'qwe_profile_theme_selected_themes_deleted' => 'Selected Themes Deleted',

	'qwe_profile_theme_form_explanation0' => 'Here you can change your profile theme.',
	'qwe_profile_theme_form_explanation1' => 'Use one of MySpace themes from the gallery or create your own CSS code to make your profile page beautiful and unique.',
	'qwe_profile_theme_adm_settings' => 'Profile Theme Settings',
	'qwe_profile_theme_per_page' => 'Themes Per Page',

	'qwe_profile_theme_themed_pages' => 'URIs of Pages, Which Are Integrated With Profile Themes',
	'qwe_profile_theme_new_page_uri' => 'New Page URI',
	'qwe_profile_theme_adm_add_new_page_uri' => 'Add New URI',
	'qwe_profile_theme_add_new_page_uri' => 'Add New Page URI Pattern',
	'qwe_profile_theme_uri_must_be_filled' => 'URI Field Is Required!',
	'qwe_profile_theme_adm_new_oage_uri_added' => 'New Page URI Pattern Added',
	'qwe_profile_theme_use_placeholder' => 'Use {PROFILE_ID} As Profile ID Place Holder. Ex: /blog/?user_id={PROFILE_ID}',
	'qwe_profile_theme_use_placeholder_nickname' => 'Use {PROFILE_NAME} As Profile Name Place Holder. Ex: /blog/{PROFILE_NAME}',
	'qwe_profile_theme_selected_uri_deleted' => 'Selected URI Deleted',
	'qwe_profile_theme_use_placeholder_id_regexp' => 'Use {REGEXP_PROFILE_ID} As Profile ID Place Holder If You Want Describe The URI By RegExp. Ex: ^\/blog\/\?user_id={REGEXP_PROFILE_ID}$',
	'qwe_profile_theme_use_placeholder_nickname_regexp' => 'Use {REGEXP_PROFILE_NAME} As Profile Name Place Holder If You Want Describe The URI By RegExp. Ex: ^\/blog\/{REGEXP_PROFILE_ID}$',
	'qwe_profile_theme_use_placeholder_my' => 'Start URI With {MY_PROFILE} To Customize Your Own Pages',
	'qwe_profile_theme_use_placeholder_my_regexp' => 'Start URI With {REGEXP_MY_PROFILE} To Customize Your Own Pages Using RegExp',
);

?>
